### ISSUE TITLE
Filter investigations by space

### ISSUE THREAD

**Issue by mason-fish** [brimsec/brim#1021]
Currently we collect history entries (or investigations) globally and show them all at once regardless of what connection or space you are on. Clicking on an investigation will rerun the search in the space that it had originally been run in. If you are working across multiple spaces then this can cause unwanted context switches.

Instead of showing all of the entries, let's filter them by space. Later, we can also add a "Saved Queries" section to the left sidebar which are space-agnostic and may be run against you current context.

**Comment by philrz** [comment]
Verified in Brim commit `f93b800`.

Per the attached video, now each Search I perform in each Space/Connection combo lands in its on set in the History panel. As I click back to Spaces I'd visited in the past, my History entries for that Space reappear and I can click on them to re-execute them.

[Verify.zip](https://github.com/brimsec/brim/files/5279985/Verify.zip)

Thanks @mason-fish!
