### ISSUE TITLE
Connection Detail view

### ISSUE THREAD

**Issue by mason-fish** [brimsec/brim#1022]
We need a view for editing existing connections. For now that only means editing the hostname, and removing the whole connection. But as we add more means of authN and naming our connections this will also be the place to edit those as well.

My initial thought was that we could access this view by clicking an `(i)`icon that sits next to the listed current connection, just to the right of the dropdown. @jameskerr I'd be curious of your thoughts about that or if you have some additional design input!

**Comment by jameskerr** [comment]
I'll gladly work on some designs for this.

**Comment by philrz** [comment]
Verified in Brim commit `83c45bd`.

Per the attached video, now when **New Connection** is selected from the drop-down, there's entries for required fields for the **Name** and **Host**, and an error is displayed if the user tries to save the settings without having entered values for one or both of the settings. Once saved, the current settings for the connection can be reviewed via the "Get info" option on the Connections drop-down, and if the Edit button is clicked there, the name/port can be changed, once again confirming they're valid and that the host is actually reachable.

[Verify.mp4.zip](https://github.com/brimsec/brim/files/5497689/Verify.mp4.zip)

The ability to _remove_ such a connection still a work-in-progress and is being tracked separately in #1191.

Thanks @mason-fish!
