### ISSUE TITLE
Replace confusing animation shown during Windows install

### ISSUE THREAD

**Issue by philrz** [brimsec/brim#1037]
When @orochford was giving his first impressions of the install experience on Windows, he was briefly thrown by the graphic that's shown during install, joking that "initially my thought was a graphic driver issue". It look like this, with animation effects that make it look like a moving cursor and blocks of code being added, perhaps simulating an IDE?

![Screenshot](https://user-images.githubusercontent.com/5934157/91892914-448b4600-ec48-11ea-82e7-bc2ae6042b2e.png)

My understanding is that this is a by-product of whatever Electron installer we currently use. I admit that I was thrown by this back when I first saw it also, since most installers pop up some kind of text-based guidance saying "Installing"... or some other animated graphic, such as Slack's which shows an animation of their logo.

While we've not received outside complaints to date about the installer experience, as the app becomes accessible to more diverse users, it'd probably be good to figure out if we can improve on this.

**Comment by philrz** [comment]
A community user also was tripped up by the installer recently, as captured in a [thread on public Slack](https://brimsec.slack.com/archives/C010DR0HHMF/p1602120311026800). They effectively had the impression that `Brim_Setup.exe` was the way to launch the app, which I now recognize is an easy mistake to make since the opaque animation gives no explicit indications that it's an installer. The fact the app launches right after the installation completes could easily give the impression that `Brim_Setup.exe` is a standalone tool that you click each time you want to run it.

**Comment by jameskerr** [comment]
Yup, that makes sense. It is spurious behavior.

**Comment by henridf** [comment]
I just installed from the Windows installer for the first time, and my first reaction was to reach out to @philrz to provide live testimonial of this weird green animation and how it appeared like something was broken.

**Comment by philrz** [comment]
Our own @henridf also got tripped up by this on Windows. A testimonial as captured on Slack:

---
> I just downloaded Brim-Setup.exe onto a fresh 2019 server, but am having trouble installing it.
> I see this green animation when i try to open the .exe which is entirely new to me....
> ![image](https://user-images.githubusercontent.com/5934157/99979546-0f305900-2d5c-11eb-94fa-ad47150a7ca6.png)
> And after some time, it ends and the application doesn't seem to be installed.
> I'm guessing I'm missing something dumb?
> Oh, now I have the brim icon on the desktop. Weird.
---

This seems pretty telling to me. In the end he deduced that it had installed ok, and indeed, if other users are noticing the same it would explain why we're not getting more active complaints about this. However, if the animation and lack of progress pop-ups is causing many users to pause and wonder if something is wrong, it's not a great on-boarding experience.

**Comment by jameskerr** [comment]
Here are the docs for the library we use. I'd recommend upgrading it to v4.0.2, then creating our own brim loading gif.

https://github.com/electron/windows-installer#usage

**Comment by philrz** [comment]
The linked PR #1478 shows an example of what the new animation looks like. As #1487 may replace what the user sees during install, this improvement may never see the light of day. But it's there for now.
