### ISSUE TITLE
Electron upgrade

### ISSUE THREAD

**Issue by alfred-landrum** [brimsec/brim#1044]
We should update Electron to most recent stable release, v10.1.1 currently. @jameskerr notes that last time we attempted an Electron upgrade, we had some issues with the Spectron framework, so the Electron update may require updating several other dependencies. (https://github.com/electron-userland/spectron/pull/631)

**Comment by philrz** [comment]
The plan is to get the work for this prepared such that we can merge it at the start of the next milestone.
