### ISSUE TITLE
Crash when no current space and network error

### ISSUE THREAD

**Issue by jameskerr** [brimsec/brim#1048]
The app will crash if zqd goes down, and there is no active space.

To reproduce:

1. Start brim
2. Click a Space
3. pkill zqd
4. Issue a search (to see the yellow "network error" message... don't dismiss it)
4. Open a new tab (while the yellow "network error" message is still visible)
5. Crash with this error message

![image](https://user-images.githubusercontent.com/3460638/92154841-4afdf700-eddb-11ea-8446-c0d12826bc04.png)

**Comment by philrz** [comment]
I also found I could reproduce the same type of error even if the yellow error message had been dismissed. If I open a new tab after zqd is killed, there's no error on the blank new tab. But if I click the Space name in the picker, then the error shows up.

**Comment by philrz** [comment]
#830 triggers an error similar to this one. Once we've addressed this issue I'll circle back and reassess the state of #830.

**Comment by jameskerr** [comment]
@philrz It looks like mason fixed this issue with 8636e293bc72eb250af12eb912ff0d67fad67da8. I'm going to mark it as closed for you to verify.

**Comment by philrz** [comment]
Verified in Brim commit `a563c51` talking to `zqd` commit `e26ffa3`.

The original repro steps are repeated in the attached video. Now when I click to open a new tab after the failure of the attempted search, there's no longer a crash. I also show how I'm able to manually restart `zqd` as it was before and click the "Retry" link and see the app successfully reconnect and show the contents of the Space.

[Verify.mov.zip](https://github.com/brimsec/brim/files/5418952/Verify.mov.zip)

Thanks @mason-fish!
