### ISSUE TITLE
Support import of nanosecond pcap files

### ISSUE THREAD

**Issue by philrz** [brimsec/brim#1068]
The capture I used in https://github.com/brimsec/zq/issues/1240 was initially generated via:

```
$ tcpdump -i ens4 -w pings.pcapnano --time-stamp-precision=nano net 192.168.1.0/24
```

[pings.pcapnano.zip](https://github.com/brimsec/brim/files/5209849/pings.pcapnano.zip)

That format is actually a variant that Brim is not yet trained to recognize:

```
$ capinfos pings.pcapnano
File name:           pings.pcapnano
File type:           Wireshark/tcpdump/... - nanosecond pcap
```

Therefore when dragged it into Brim commit `73d51c1`, the user experience:

![image](https://user-images.githubusercontent.com/5934157/92941096-c9bee980-f404-11ea-9567-203948046c9f.png)

Wireshark and Zeek both happily read it, though. I was able to turn it into usable test data for https://github.com/brimsec/zq/issues/1240 by opening it in Wireshark and saving it as a pcapng.

I can see by:

https://github.com/brimsec/brim/blob/63233ef59e46ddf1f4630fe205f3474fe7fd33cb/src/js/brim/ingest/detectFileType.js#L4-L7

...where we recognize the file signatures of capture formats, and the signature `4d 3c b2 a1 ` I observe for this capture is not in that list.

```
hexdump pings.pcapnano | head -1
0000000 4d 3c b2 a1 02 00 04 00 00 00 00 00 00 00 00 00
```

The format does not seem to be widely discussed online, but I do see one of the well-known Wireshark developers speaking of this signature at https://osqa-ask.wireshark.org/questions/51702/magic-numbers-for-supported-capture-files-for-wireshark, so it seems appropriate for us to add it to our list.

**Comment by philrz** [comment]
The video below shows this is now working as of Brim commit `9794080` which talks to `zqd` commit `e322b38`. Specifically, this gets us through the import phase, though actual extraction of pcaps from a nanosecond pcap is not working until https://github.com/brimsec/zq/issues/1240 is adressed.

[Verify.zip](https://github.com/brimsec/brim/files/5211363/Verify.zip)

**Comment by jameskerr** [comment]
Thanks @philrz !
