### ISSUE TITLE
remove usage of make in package.json

### ISSUE THREAD

**Issue by alfred-landrum** [brimsec/brim#1076]
The `deps:zealot` scripts entry in package.json is `cd zealot && make bundle`. This currently works in our Windows CI because the Windows GitHub Actions environment has a `make.exe` that's a copy of `mingw32-make.exe` from a Chocolatey install of mingw. However, that may not be available in a typical Windows javascript dev environment. We should change the zealot code to just use package.json scripts to build the bundle, run tests, etc.

**Comment by jameskerr** [comment]
Yup, this makes sense.

**Comment by alfred-landrum** [comment]
Fixed in #1075
