### ISSUE TITLE
Window load does not set host and port query params

### ISSUE THREAD

**Issue by mason-fish** [brimsec/brim#1079]
The result of this is that if you close a window that was looking at a non-default connection's space and re-open, it loads up the default zqd into zealot but then cannot find the previously viewed space and the user sees this

![image.png](https://images.zenhubusercontent.com/59b953feb0222d5de4779702/381fa417-3156-466c-9058-034159d57463)

**Comment by philrz** [comment]
Verified in Brim commit `0b26536`.

I've attached a repro video as of Brim GA tagged `v0.17.0`. Per the opening remarks, all it required was being connected to a remote `zqd` and having browsed to one of those remote Spaces before quitting the app. Then when I relaunched the app, I was immediately greeted with the "Space does not exist" error.

[Repro.zip](https://github.com/brimsec/brim/files/5285820/Repro.zip)

Now running Brim commit `0b26536` in Dev mode, when I repeat the same steps, after doing `npm start` to relaunch the Brim app after having closed it, I'm immediately brought into the remote Space I was at when I closed the app.

[Verify.zip](https://github.com/brimsec/brim/files/5285847/Verify.zip)

Thanks @mason-fish!
