### ISSUE TITLE
Provide UI indication for newConnection status check

### ISSUE THREAD

**Issue by mason-fish** [brimsec/brim#1080]
On the newConnection modal, after hitting 'Connect', we keep the modal open until the status check succeeds (and if it doesn't we display errors within the modal), but during this status check there is no indication that anything is happening. Let's add a spinner next to the connect button while we wait for the response.

**Comment by mason-fish** [comment]
After further investigating, there are a couple things actually happening here:
1. There is a delay after hitting "connect" in this modal, but in this case it is not actually caused by the network request (which should generally be v quick for a public status endpoint served locally), though adding a spinner still seems worthwhile for scenarios where this actually occurs over the wire and with authN. In fact, this delay occurs in all of our modals as part of the "exit" animation. I personally find the response to be much better by removing that.

2. There is also a state and rendering related issue where this modal does not close and gets stuck on the page. This can be reproduced when coming from the search page and creating a new conn. The new conn is created successfully, and the redux state is updated properly to set the modal `name` to an empty string, but it appears that the DOM is not being updated appropriately even though the modal component is listening to that redux state change appropriately.

**Comment by philrz** [comment]
Verified in Brim commit `f93b800`.

I was not familiar with the original issue, so I took a step back and did a repro with Brim GA tagged `v0.17.0` talking to GA `zq` tagged `v0.21.0`. I ran `zqd` inside a Linux VM in VirtualBox with a port forwarding rule that redirected `localhost:9999` traffic on my Mac to the port `9867` inside the VM. I then started `zqd` in the Linux VM via:

```
# /usr/lib/brim/resources/app/zdeps/zqd listen -l :9867 -data /home/phil/.config/Brim/data/spaces -config /home/phil/.config/Brim/zqd-config.yaml -zeekrunner /usr/lib/brim/resources/app/zdeps/zeek/zeekrunner
```

I also wanted to introduce some network delay, so using some tips I found online, I ran this command line in the Linux VM to introduce a 5-second delay to every packet traversing the Ethernet interface in/out of the VM.

```
# sudo tc qdisc add dev enp0s3 root netem delay 5000ms
```

Now from the Brim on my Mac I could try to connect to `localhost:9999` and experience the symptom as originally described where, after clicking Connect, the window shows no sign anything is happening but hangs quietly and does connect after several seconds. This is shown in this first attached video.

[Repro.zip](https://github.com/brimsec/brim/files/5279939/Repro.zip)

I then repeated the same connection attempt using Brim commit `f93b800`. As you can see in the attached video, now the Connect button turns into a spinner and gives me something to stare at while I'm waiting. 😄 

[Verify.zip](https://github.com/brimsec/brim/files/5279944/Verify.zip)

Thanks @mason-fish!
