### ISSUE TITLE
Add and use name field for connections

### ISSUE THREAD

**Issue by mason-fish** [brimsec/brim#1085]
We are currently using connection id's as the display name, and that id is the `{host}:{port}` combo. Let's add a name field which can default to just use the host but otherwise be assigned any string value.

**Comment by philrz** [comment]
It wasn't clear to me how this related to #1022, so I asked @mason-fish offline. I'm just recording his answer here for my own benefit if I forget and have the same question again later:

> The design in #1022 includes this connection naming feature. Technically we can decouple them and add the naming feature in after #1022.

**Comment by philrz** [comment]
Verified in Brim commit `00f809a`. In the attached video I add a remote connection and give it a name, which appears in the picker from which I can choose to connect between the configured local and remote services.

[Verify.mov.zip](https://github.com/brimsec/brim/files/5419607/Verify.mov.zip)

Thanks @mason-fish!
