### ISSUE TITLE
Connection Detail view design

### ISSUE THREAD

**Issue by mason-fish** [brimsec/brim#1086]
This ticket tracks the UI design work necessary for #1022

**Comment by jameskerr** [comment]
Here is a link to the connection detail designs: https://www.sketch.com/s/4b2957a2-910e-403c-9fda-617de055c061/p/connection-detail

**Comment by philrz** [comment]
@mason-fish: While revisiting some old open issues, I came across #710. Some of the motivations/details have changed, but I think in a recent group discussion we similarly touched on the usefulness of having info like storage consumed included in the summary details for a Space. Working with `zapi` implies that this data is already being returned via the API, e.g. `size` and `pcap_size` below:

```
$ zapi ls -l
all.pcap
  id:           sp_1iTHBt3PsSrcORfot6HSFSHWMvO
  name:         all.pcap
  data_path:    file:///Users/phil/work/brim/run/data/spaces/sp_1iTHBt3PsSrcORfot6HSFSHWMvO
  storage_kind: filestore
  span:         2015-03-05T14:25:12Z+931h9m31.789035001s
  size:         74.29MB
  pcap_support: true
  pcap_size:    4.38GB
  pcap_path:    file:///Users/phil/pcap/all.pcap
  parent_id:    
...
```

Is this something easy to add to the design, if it's not there already?

**Comment by mason-fish** [comment]
@philrz since this ticket focuses on `connection` detail were you imagining that we aggregate all of a connection's spaces' consumed storage and present that total?

**Comment by philrz** [comment]
Oh shoot, right you are @mason-fish. Yeah, ignore my question, I guess. Perhaps at some point in the future we'd add some kind of "Space Detail" view to cover what's described in #710. I see now that's orthogonal.
