### ISSUE TITLE
Clicking Brim dock icon brings up an additional window

### ISSUE THREAD

**Issue by philrz** [brimsec/brim#1118]
Starting with GA Brim tagged `v0.18.0`, I've noticed that on macOS when the Brim app is already running and there's a window open, clicking the Brim icon in the dock opens yet another separate window. In GA Brim tagged `v0.17.0` and other earlier versions, this did not happen. With those older versions, clicking the icon in the dock would simply make sure that the Brim window that's already open is maximized and in the foreground, which is more in line with how other macOS apps tend to behave,

Here's a video reproducing the problem in `v0.18.0`:

[Repro.zip](https://github.com/brimsec/brim/files/5341821/Repro.zip)

Here's a video showing the behavior in `v0.17.0`:

[v0.17.0.zip](https://github.com/brimsec/brim/files/5341847/v0.17.0.zip)

**Comment by jameskerr** [comment]
I see, yup this is a bug.

**Comment by philrz** [comment]
Verified in Brim commit `83c45bd`.

Per the attached video, clicking the Brim dock icon after the app is already launched no longer opens a separate window. Instead it makes sure the open window(s) are brought to the foreground, but does not open any additional window.

[Verify.zip](https://github.com/brimsec/brim/files/5497739/Verify.zip)

Thanks @jameskerr!
