### ISSUE TITLE
macos zar integration test failing

### ISSUE THREAD

**Issue by alfred-landrum** [brimsec/brim#1130]
Here's an example failure run:
https://github.com/brimsec/brim/runs/1233923504?check_suite_focus=true#step:18:111

From a slack thread discussing it:
`I'm just trying this on master; I don't think it's a problem with the zar calls. I think the ingestFile step in the zar test doesn't quite complete before the test continues, and that seems to cancel the ingest & delete the space. Later on, the test looks for the space from the ingest, and doesn't find it`
https://brim-labs.slack.com/archives/C9560J0TY/p1602291398053700

**Comment by philrz** [comment]
Per the text in the description, this was ultimately fixed via #1134 that pops up an notice when import is complete, and the test can now explicitly wait on the notice. The notice also provides a handy visual cue for the user.
