### ISSUE TITLE
Enable connection removal/deletion

### ISSUE THREAD

**Issue by mason-fish** [brimsec/brim#1191]
The last missing operation on connections/clusters is to allow users to remove them.

This should include a sort of on-cascade handling of empty states for any existing search tabs or windows which are referring to the connection by notifying the user of this change, similar to how we handle space deletion.

For now, we should also prohibit the user from removing connections to `localhost:9867` since the app depends on always having it's own local zqd instance running

**Comment by philrz** [comment]
Verified in Brim commit `c7a38cf` talking to `zqd` commit `d4587a9`

As shown in the attached video, now when the user selects the "Get Info" option for a connection, there's a red "Remove" link available. When the link is clicked and "Ok" is clicked, the connection is removed. The user is then brought to a "Choose a Connection" screen to determine what to show instead. Finally, the "Get Info" option for the local `zqd` lacks a "Remove" option.

[Verify.zip](https://github.com/brimsec/brim/files/5592284/Verify.zip)

Thanks @mason-fish!
