### ISSUE TITLE
closing last window leaves lingering process, unable to start Brim afterwards

### ISSUE THREAD

**Issue by alfred-landrum** [brimsec/brim#1204]
On my Windows 10 machine with the v0.19.0 Brim release, if I close the last open Brim window either by using the taskbar 'Close Window' option, or by closing the window via the upper-right "X", the window disappears, and Brim looks like it has quit. However, I then can't start Brim up again by clicking on its icon.

If I check Task Manager, I see that after quitting the last window, there are still some lingering 'Brim' processes left running, and I assume that means that the application did not in fact quit. If I manually quit those tasks in Task Manager, I can then launch Brim with the usual icon double click.

**Comment by philrz** [comment]
FWIW, in my own repro, I noticed an orphaned `zqd` process in addition to the lingering Brim processes. It's easiest to see in the "Details" tab of the Task Manager.

**Comment by philrz** [comment]
Verified in GA Brim tagged `v0.19.0`.

The original symptom is captured in the first video below. Using a failed `v0.19.0` release candidate, when quitting Brim on Windows, you could see the lingering Brim and `zqd` processes left behind in the Task Manager. The app was unable to reopen after having quit it.

[Repro.zip](https://github.com/brimsec/brim/files/5533273/Repro.zip)

Now with the GA Brim tagged `v0.19.0`, we can see that upon quitting, all Brim and `zqd` processes all disappear from the Task Manager, and the app can be reopened as usual.

[Verify.zip](https://github.com/brimsec/brim/files/5533274/Verify.zip)

Thanks @jameskerr!
