### ISSUE TITLE
Suricata failures when running deb/rpm-installed Brim

### ISSUE THREAD

**Issue by henridf** [brimsec/brim#1216]
The Linux packages install into non-writeable system dirs (such as `/usr/lib/...` or `/var/lib/..`). This leads to two issues:

- The suricatarunner script generates a suricata config at run time, writing it in its own dir. This fails as the dir is non-writable.
- suricata-update similarly expects to be able to write into the `/var/lib/...` dir where the rules are installed.

To solve this, we should use the Electron `appDir` for both the Suricata conf and the rules. Brim can communicate via an env var to the runners mentioned above.

**Comment by philrz** [comment]
Addressed via https://github.com/brimsec/build-suricata/pull/29.
