### ISSUE TITLE
Intermittent problems launching Brim v0.19.0+ on a Windows VM over Remote Desktop

### ISSUE THREAD

**Issue by philrz** [brimsec/brim#1218]
As part of some test work, @henridf happened to try installing GA Brim tagged `v0.19.0` onto a Windows 2019 Server VM on Google Cloud and found it would not start. I reproduced this on a Windows Server 2019 Datacenter VM and saw the same. It comes up with a white blank screen. The DevTools console shows no error messages.

Other details:
* It is intermittent. Sometimes it _does_ come up ok.
* While I initially spotted it on the first app launch that happens at the tail end of installation, I've also reproduced it by manually killing all processes from the hung app via the Task Manager and relaunching it via the icon on the desktop.
* Thinking the problem might be unique to the Windows builds on Google Cloud, on AWS EC2 I created a Microsoft Windows Server 2019 Base VM, but it also failed to start `v0.19.0`, showing the same blank white screen.
* I've since reproduced the same intermittent failure on a Windows Server 2016 Datacenter VM on Google Cloud and a Windows 10 VM in Azure as well.
* I _can't_ seem to reproduce the problem with GA Brim `v0.18.0`. I've tested this on both Windows Server 2016 & 2019 Datacenter VMs on Google Cloud, 
* As part of Suricata testing, I've had reason to test with other release artifacts based on Brim `master` commits since GA v0.19.0 was released and the symptom reproduces in those as well.
* I've _never_ seen this problem on my Windows 10 laptop that I use for most Brim testing, leading me to wonder if triggering the problem is somehow specific to when working on a VM and/or over Remote Desktop.

This particular "blank white screen" is a little different from others we've seen in the past, since it _does_ have the menu bar present. Example:

![image](https://user-images.githubusercontent.com/5934157/100555081-14a30d00-324e-11eb-94af-38f174b284a8.png)

Here's an example of how the logging looks when it's in this state:

```
C:\Users\phil\AppData\Roaming\Brim\logs>dir
 Volume in drive C has no label.
 Volume Serial Number is DEA0-1188

 Directory of C:\Users\phil\AppData\Roaming\Brim\logs

11/29/2020  10:17 PM    <DIR>          .
11/29/2020  10:17 PM    <DIR>          ..
11/29/2020  10:17 PM             1,059 main.log
11/29/2020  10:17 PM                 0 zqd-core.log
               2 File(s)          1,059 bytes
               2 Dir(s)  33,007,079,424 bytes free
```

The contents of the app's non-zero `main.log`:

```
C:\Users\phil\AppData\Roaming\Brim\logs>type main.log
[2020-11-29 22:17:53.188] [info] app paths: getAppPath=C:\Users\phil\AppData\Local\Brim\app-0.19.0\resources\app userData=C:\Users\phil\AppData\Roaming\Brim logs=C:\Users\phil\AppData\Roaming\Brim\logs
[2020-11-29 22:17:56.319] [info] app paths: getAppPath=C:\Users\phil\AppData\Local\Brim\app-0.19.0\resources\app userData=C:\Users\phil\AppData\Roaming\Brim logs=C:\Users\phil\AppData\Roaming\Brim\logs
[2020-11-29 22:17:56.431] [info] zqd core log C:\Users\phil\AppData\Roaming\Brim\logs\zqd-core.log
[2020-11-29 22:17:56.442] [info] zqd access log C:\Users\phil\AppData\Roaming\Brim\logs\zqd-access.log
[2020-11-29 22:17:56.451] [info] zqd config C:\Users\phil\AppData\Roaming\Brim\zqd-config.yaml
[2020-11-29 22:17:56.471] [info] spawning zqd: C:\Users\phil\AppData\Local\Brim\app-0.19.0\resources\app\zdeps\zqd.exe listen -l localhost:9867 -data C:\Users\phil\AppData\Roaming\Brim\data\spaces -config C:\Users\phil\AppData\Roaming\Brim\zqd-config.yaml -zeekrunner C:\Users\phil\AppData\Local\Brim\app-0.19.0\resources\app\zdeps\zeek\zeekrunner.exe
```

Indeed, despite the zero-length `zqd-core.log`, indeed `zqd` has been successfully launched by Brim, as evidenced by the fact that I can access it directly on its listening port.

![image](https://user-images.githubusercontent.com/5934157/100555148-73688680-324e-11eb-836e-95154519c29c.png)

I checked the DevTools console hoping to find an error, but it's completely blank.

![image](https://user-images.githubusercontent.com/5934157/100555177-9c891700-324e-11eb-977d-67e2e683b988.png)

Also, when it's in this state, I _can_ select **File > New window** and obtain a working app window.

![image](https://user-images.githubusercontent.com/5934157/100555203-b62a5e80-324e-11eb-8853-c444251c5195.png)

If I close all the other Brim windows and am back to the single blank white one, I find it doesn't close when I hit the "X" in the upper-right, nor if I attempt to select **File > Exit**. Selecting **View > Reload** and **View > Force Reload** also don't appear to have any effect.

When I look in the Task Manager while it's in this state, here's what I see in terms of the count of Brim processes:

![image](https://user-images.githubusercontent.com/5934157/100555251-06a1bc00-324f-11eb-8e00-fd88eb9b3d56.png)

If I right-click the top "Brim" in the Task Manager and select "End task", it does kill the window, but I've noticed it leaves behind a Brim process "dropping" that I still need to kill manually. The `zqd` process did go away when the main Brim task was killed, though.

![image](https://user-images.githubusercontent.com/5934157/100555273-318c1000-324f-11eb-8474-6338fcad6733.png)

Notice that it's continuing to burn ~20% CPU despite it being a standalone process with no visible window. What the heck do we think it's doing? 😄

**Comment by philrz** [comment]
While the description above was accurate as of what I saw on that first day, I've since tried other variations and had different results. Today I ultimately saw the blank white startup screen on a Windows 2016 Server VM in Google Cloud as well as a Windows 10 VM in Azure.

I also have since circled back to repro again on a Windows 2019 Server VM in Google Cloud and have a bit more info on the symptom I'm seeing there. A detail that's perhaps important is that I'm not seeing an _absolute_ white screen, but, rather, the pull-down menu bar is present, but the contents are blank, like this:

![image](https://user-images.githubusercontent.com/5934157/100040449-24d56b00-2dbc-11eb-8328-e7db81ba3434.png)

Furthermore, I found at that point that I could select **File > New Window** and that _does_ bring up a normal/operating Brim window into which I can import pcaps and otherwise work normally.

Maybe it's a problem unique to doing installations over Remote Desktop? I've admittedly done most of my Windows testing on my local Windows 10 laptop, so if this has been an issue for some time I've had fewer opportunities to notice it.

**Comment by philrz** [comment]
Good news, I think! Having learned what we just did from a similar symptom on macOS in #1242, I tried launching the v0.19.0 `Brim.exe` from the command line on a Windows Server 2016 via:

```
C:\Program Files>C:\Users\phil\AppData\Local\Brim\Brim.exe --disable-gpu
```

Now it came up healthy in 10 out of 10 launches. I then did a set of 10 launch attempts on the same VM via:

```
C:\Program Files>C:\Users\phil\AppData\Local\Brim\Brim.exe
```

And that _failed_ in 10 out of 10 launch attempts, each time with me having to kill the processes in Task Manager in two rounds.

Finally, after that, I did _another_ set of 10 launches with `--disable-gpu` and those succeeded yet again.

I did a little web searching and found https://github.com/electron/electron/pull/5889 that indicates we could potentially invoke this without a command line option.

**Comment by jameskerr** [comment]
Great! I'm glad you found the issue. I'd like to see if any of the App's animations are effected by disabling the GPU acceleration. That's the only feature I see being effected. If it all seems the same, let's do it for all instances. But if there is a difference, maybe we can disable it if certain conditions are met?

**Comment by philrz** [comment]
I'm certainly prepared to defer to your instincts here, especially because I don't know how much effort is involved with determining if the app's animations are affected, or if we went for the "disable under certain conditions" approach, if it's easy to determine those conditions so we can invoke it where it counts. Thus far I've only looked at this from a high-level supportability perspective, which is that starting with v0.19.0, we now have this "blank startup" issue showing up on multiple platforms, and when it happens it doesn't give the user anything much to go on in terms of error messaging or workarounds. Given the prevalence of virtualizing in the cloud era, it feels like an accident waiting to happen, and I'm just glad nobody else seems to have stumbled onto it yet. If in the worst case disabling the GPU made everything a little slower in all cases, it's a trade-off I'd personally accept, but I also respect the desire to measure it first. If it was 10x slower or something it does seem like something we'd want to know. (cc: @alfred-landrum if he has any instincts on how many cycles to allocate here.)

**Comment by alfred-landrum** [comment]
@jameskerr : Would you please list the animations we should check?

**Comment by jameskerr** [comment]
I agree Phil, the pros outweigh the cons it seems.

The animations to check on would be:

The modal animation
The "import complete" notice
The histogram filling in
The yellow error notice

That's enough to get a sense if thing are drastically affected. I don't think they will be.

**Comment by philrz** [comment]
Verified using the GA Brim `v0.20.0` release candidate by successfully launching Brim 10 times in a row on a Windows 2019 VM on Google Cloud. Thanks @jameskerr!
