### ISSUE TITLE
Zoom-in freezes Brim

### ISSUE THREAD

**Issue by philrz** [brimsec/brim#1256]
I happened to be giving a demo today on my Mac of a recent Brim commit to show off Suricata and tried zooming in via Command+ and it froze the app. I just did a binary search to see where it broke and I can confirm that thankfully the last GA release `v0.20.0` is healthy, but the more recent commit where it started freezing is `c7d34e8`, which is associated with #1247 (cc: @jameskerr).

**Comment by jameskerr** [comment]
I've discovered that my incorrect use of a ResizeObserver class within a hook is causing an infinite loop. I was  able to isolate the one line that caused this. Fix coming shortly.

**Comment by philrz** [comment]
Verified in Brim commit `4bef0e7`.

Per the attached video, zoom in & out now work properly without freezing the app.

[Verify.zip](https://github.com/brimsec/brim/files/5691475/Verify.zip)

Thanks @jameskerr!
