### ISSUE TITLE
change how tests detect import completion

### ISSUE THREAD

**Issue by alfred-landrum** [brimsec/brim#1274]
In a slack discussion about some flakiness we've seen with new suricata verification tests, @jameskerr said:

> Some more info, the pop notice is displayed for 4 seconds, then it disappears. Checking for the presence of it seems to be working well enough to determine if an import is complete, but I’ve always wondered if sometimes spectron waits too long to start checking for the existence of it. If that happened the test would fail with “couldn’t find the pop notice”. Anyway, there’s a little upload of thoughts I’ve had in the past.
> alfred  2 hours ago
Is there a different way the tests could check for pcap import being done that doesn't rely on catching the popup window? Some variable on the DOM, ... ?
> Kerr  1 hour ago
Yeah, that’s an idea. Set a persistent attribute on the dom.

**Comment by philrz** [comment]
As reported on Slack, I've been able to successfully repro a failure regarding the "pop notice" on a local run of the CI on my Mac laptop. Since we'd previously seen the failure only on CI runs (right?), I was trying to see if I could make my laptop behave anything more like the Actions Runner hosts, with the first idea being keeping the CPU highly constrained, which I did by running 15 instances of `cat /dev/urandom > /dev/null &` in the background before starting a test. The failures I've seen are in `ingest.test.ts`, so my understanding is that these are not Suricata specific (the pcaps involved don't seem to trigger the creation of Suricata alerts). But Suricata is still processing the pcaps, so the additional load it generates might be contributing to the likelihood of failure (further aggravating a timing issue that the excess CPU load was also aggravating?)

There's video evidence of the failing run at:

https://www.youtube.com/watch?v=3Z2RaPKkYTE&feature=youtu.be

**Comment by philrz** [comment]
Verified in Brim commit `74f0f19`.

I verified by doing a 2x2 combination of repeated (20 times per set) CI-like integration test runs locally on my Mac laptop. There were two sets at commit `2b45a97` that came right before the change, and two sets at commit `74f0f19`. At each commit one of the sets was "unburdened" (no excess processes running to burn CPU) and the other set was "burdened" (15x instances of the `cat /dev/urandom > /dev/null &` as described in the original repro notes/video). An example of one of the sets:

```
git checkout 2b45a97
npm install
npm run build
NUM=1 ; while [ $NUM -le 20 ]; do npm run itest -- --ci --forceExit 2>&1 | tee -a 2b45a97-unburdened.out; killall zqd; killall Wireshark; rm -rf "$HOME/work/brim/run"; NUM=$(expr $NUM + 1); done
```

Full results from each set:
* [2b45a97-unburdened.out.gz](https://github.com/brimsec/brim/files/5810760/2b45a97-unburdened.out.gz)
* [2b45a97-burdened.out.gz](https://github.com/brimsec/brim/files/5810762/2b45a97-burdened.out.gz)
* [74f0f19-unburdened.out.gz](https://github.com/brimsec/brim/files/5810763/74f0f19-unburdened.out.gz)
* [74f0f19-burdened.out.gz](https://github.com/brimsec/brim/files/5810766/74f0f19-burdened.out.gz)

Summarizing what's in there, what we observe is that before the fix, even unburdened, we saw one failure out of 20 runs.

```
$ gzcat 2b45a97-unburdened.out.gz | grep "Test Suites"
Test Suites: 9 passed, 9 total
Test Suites: 1 failed, 8 passed, 9 total
Test Suites: 9 passed, 9 total
Test Suites: 9 passed, 9 total
Test Suites: 9 passed, 9 total
Test Suites: 9 passed, 9 total
Test Suites: 9 passed, 9 total
Test Suites: 9 passed, 9 total
Test Suites: 9 passed, 9 total
Test Suites: 9 passed, 9 total
Test Suites: 9 passed, 9 total
Test Suites: 9 passed, 9 total
Test Suites: 9 passed, 9 total
Test Suites: 9 passed, 9 total
Test Suites: 9 passed, 9 total
Test Suites: 9 passed, 9 total
Test Suites: 9 passed, 9 total
Test Suites: 9 passed, 9 total
Test Suites: 9 passed, 9 total
Test Suites: 9 passed, 9 total
```

When the system was burdened with all the excess CPU load, the failure rate increased significantly, in line with the original repro experience.

```
$ gzcat 2b45a97-burdened.out.gz | grep "Test Suites"
Test Suites: 9 passed, 9 total
Test Suites: 9 passed, 9 total
Test Suites: 1 failed, 8 passed, 9 total
Test Suites: 1 failed, 8 passed, 9 total
Test Suites: 1 failed, 8 passed, 9 total
Test Suites: 9 passed, 9 total
Test Suites: 1 failed, 8 passed, 9 total
Test Suites: 9 passed, 9 total
Test Suites: 1 failed, 8 passed, 9 total
Test Suites: 9 passed, 9 total
Test Suites: 2 failed, 7 passed, 9 total
Test Suites: 1 failed, 8 passed, 9 total
Test Suites: 1 failed, 8 passed, 9 total
Test Suites: 1 failed, 8 passed, 9 total
Test Suites: 1 failed, 8 passed, 9 total
Test Suites: 9 passed, 9 total
Test Suites: 9 passed, 9 total
Test Suites: 9 passed, 9 total
Test Suites: 1 failed, 8 passed, 9 total
Test Suites: 1 failed, 8 passed, 9 total
```

Then with the benefit of the fix, it ran clean in 20 out of 20 runs both unburdened _and_ when burdened with the excess CPU load.

```
$ gzcat 74f0f19-unburdened.out.gz | grep "Test Suites"
Test Suites: 9 passed, 9 total
Test Suites: 9 passed, 9 total
Test Suites: 9 passed, 9 total
Test Suites: 9 passed, 9 total
Test Suites: 9 passed, 9 total
Test Suites: 9 passed, 9 total
Test Suites: 9 passed, 9 total
Test Suites: 9 passed, 9 total
Test Suites: 9 passed, 9 total
Test Suites: 9 passed, 9 total
Test Suites: 9 passed, 9 total
Test Suites: 9 passed, 9 total
Test Suites: 9 passed, 9 total
Test Suites: 9 passed, 9 total
Test Suites: 9 passed, 9 total
Test Suites: 9 passed, 9 total
Test Suites: 9 passed, 9 total
Test Suites: 9 passed, 9 total
Test Suites: 9 passed, 9 total
Test Suites: 9 passed, 9 total

$ gzcat 74f0f19-burdened.out.gz | grep "Test Suites"
Test Suites: 9 passed, 9 total
Test Suites: 9 passed, 9 total
Test Suites: 9 passed, 9 total
Test Suites: 9 passed, 9 total
Test Suites: 9 passed, 9 total
Test Suites: 9 passed, 9 total
Test Suites: 9 passed, 9 total
Test Suites: 9 passed, 9 total
Test Suites: 9 passed, 9 total
Test Suites: 9 passed, 9 total
Test Suites: 9 passed, 9 total
Test Suites: 9 passed, 9 total
Test Suites: 9 passed, 9 total
Test Suites: 9 passed, 9 total
Test Suites: 9 passed, 9 total
Test Suites: 9 passed, 9 total
Test Suites: 9 passed, 9 total
Test Suites: 9 passed, 9 total
Test Suites: 9 passed, 9 total
Test Suites: 9 passed, 9 total
```

Looking good! Thanks @jameskerr!

**Comment by jameskerr** [comment]
Wow @philrz thank you for the thorough verification!
