### ISSUE TITLE
"proto" field appearing to the left of the "alert" tile

### ISSUE THREAD

**Issue by philrz** [brimsec/brim#1292]
A couple of us have noticed that in GA Brim `v0.21.0`, on views that show a mix of multiple record types, the `proto` field sometimes appears to the left of the `alert` tile. The ordering in the record definition in the ZNG is such that `alert` is still leftward of `proto`, so it seems this ordering is somehow being caused by the app.

![image](https://user-images.githubusercontent.com/5934157/102700671-606d2480-4204-11eb-8c74-d2dfa7ccee26.png)

**Comment by jameskerr** [comment]
Yes, the app does some ordering of fields. We'll get that fixed.

**Comment by philrz** [comment]
It looks like the fix for this in #1310 was not effective, so, reopening.

Briefly revisiting a consistent repro as it stood in Brim GA tagged `v0.21.1`, yo can import https://archive.wrccdc.org/pcaps/2018/wrccdc.2018-03-23.010014000000000.pcap.gz (uncompressed) and execute a search for `"1:fwao+GwBt8XdJrY5AEkSdxJlyrM="`.

![image](https://user-images.githubusercontent.com/5934157/103701343-b3600f00-4f5a-11eb-9827-53827ed0f13d.png)

As of Brim commit `8bac79c` (which is post-merge #1310), the symptom seems to remain.

![image](https://user-images.githubusercontent.com/5934157/103701525-04700300-4f5b-11eb-838c-478bbe003435.png)

**Comment by philrz** [comment]
Verified in Brim commit `d374a86`.

Repeating the repro steps in the most recent comment above, now we the `_path` and `event_type` fields are both displayed directly to the right of the `ts` timestamp.

![image](https://user-images.githubusercontent.com/5934157/104075484-c1669780-51c7-11eb-96c0-0081bd42b901.png)

Thanks @jameskerr!
