### ISSUE TITLE
Make cloud auth work in Brim

### ISSUE THREAD

**Issue by philrz** [brimsec/brim#1309]
Once https://github.com/brimsec/zq/issues/1886 is implemented, the Brim app will need to take advantage of it. It's our expectation that in the first phase, we'll manually sign up users: If we want to give early cloud service access to someone, we'll have a tool that creates the tenant/user in Auth0 and sends them an invite email. They'll then be able to follow instructions/links in the email to authenticate and be landed in Brim such that they can begin importing logs, running queries, etc.

(In a future iteration, we'll likely also want to enable easy self-signup, such as an option in the app to "Click here to sign up for a free tier of the cloud service". We expect this would trigger a variation of what's described above, effectively creating an "invite yourself" email, similar to what we see in tools like Slack.)

**Comment by alfred-landrum** [comment]
I discussed how to break this down with @mason-fish : he's going to file one or more smaller tickets that build up the Brim application authentication support.

**Comment by mason-fish** [comment]
https://github.com/brimsec/zq/issues/1902
