### ISSUE TITLE
Edit Pin Upgrades

### ISSUE THREAD

**Issue by jameskerr** [brimsec/brim#1317]
As a result of chatting about some existing pin bugs, Mason and I discussed a brighter future for the pins UI. This was the result:

When clicking a pin to edit it, turn that pin into a small input in place. Do not reuse the search box to edit the pin. Display a checkbox, or hit enter to submit your changes to the pin. When done, move focus back to the search box, but do not issue a search. 

This will allow us to remove the "last search box" special pin at the end.

This will also allow us to remove the editing index from the search bar reducer. 

See if the searchBar.previous piece of state can be removed too.

**Comment by philrz** [comment]
Verified in Brim commit `41fe1df`.

Circling back to commit `3f659eb` to capture the state things were in before the changes in the linked PR, in the video below we walk through some standard demo steps. As described by @jameskerr above, the search box was being used to edit the pin, and the rightmost search term was always present alongside the pins as a could-be-pinned item.

https://user-images.githubusercontent.com/5934157/112382805-8a256400-8ca9-11eb-8ee3-cc3ba772c664.mp4

Now in commit `41fe1df`, we see the new behavior where editing of the pin is done within the pin itself, and the active term in the search box is no longer duplicated alongside the list of pins.

https://user-images.githubusercontent.com/5934157/112383119-f3a57280-8ca9-11eb-867f-d983eafa789f.mp4

Looks good! Thanks @jameskerr!
