### ISSUE TITLE
Hide archive index search dropdown

### ISSUE THREAD

**Issue by alfred-landrum** [brimsec/brim#1355]
We won't be ready to expose index searches for archive backed spaces in the short term. Before we flip our default from file to archive storage, we need to hide/remove the search dropdown that allows index searches:

![image.png](https://images.zenhubusercontent.com/5976d48561b4ca3b0a758e87/1659b4a4-d276-48a9-9b24-5c3bf0402a0d)

**Comment by philrz** [comment]
Verified in Brim commit `7a7f673`.

Revisiting a repro in GA Brim tagged `v0.23.0`, after importing data to an archive Space, a pull-down selector was then visible to toggle between "Event" and "Index" searches.

https://user-images.githubusercontent.com/5934157/106971540-fb15ba00-6703-11eb-8d40-a00f875dd07a.mp4

Now in Brim commit `7a7f673`, the pull-down selector is no longer visible.

https://user-images.githubusercontent.com/5934157/106971568-0668e580-6704-11eb-96b9-ba4bd166546c.mp4

Thanks @mason-fish!
