### ISSUE TITLE
Arrows in sidebar initialize to closed even if they are open

### ISSUE THREAD

**Issue by jameskerr** [brimsec/brim#1384]
Each sidebar section sets its "isOpen" to undefined the first time it's rendered which. This results in the arrows facing the wrong way. They should all be facing downward.

![Pasted Graphic.png](https://images.zenhubusercontent.com/5e8cea85d10cba8a99efeb34/27df95f6-747d-4a47-b33d-6fccac35f0d2)

**Comment by philrz** [comment]
Verified in Brim commit `7a7f673`.

I'd never witnessed this problem myself, so I took a step back and did a quick repro in GA Brim tagged `v0.23.0`. Starting from a clean app state, I imported a small pcap and the arrows in the sidebar panels were all facing downward, which seemed ok. However, when I opened a new tab they started out all closed, and even when I selected a Space and the Query Library was populated, they remained closed, which indeed looks wrong.

https://user-images.githubusercontent.com/5934157/106969497-c56ed200-66ff-11eb-90c6-d4f8efa561ff.mp4

Repeating the same steps on Brim commit `7a7f673`, now the arrows are "open" when I click to the new tab.

https://user-images.githubusercontent.com/5934157/106969524-d6b7de80-66ff-11eb-8948-dd62329237e6.mp4

Thanks @jameskerr!
