### ISSUE TITLE
Create Default Security Summary Tiles

### ISSUE THREAD

**Issue by jameskerr** [brimsec/brim#1392]

**Comment by orochford** [comment]
Here are my suggested queries and views:

Zeek
Clean Overview without conn, reporter and capture_loss
_path!="conn" _path!="capture_loss" _path!="reporter" | count() by _path | sort -r

Top hosts by throughput
_path=conn | put total_bytes = orig_bytes + resp_bytes | sort -r total_bytes | cut id, orig_bytes, resp_bytes, total_bytes

_path=dns | count() by query | sort -r

If present, top files
filename!=null | cut _path, tx_hosts, rx_hosts, mime_type, filename, md5, sha1

If present, top windows networking activity
_path=~smb* OR _path=dce_rpc | cut id.orig_h, id.resp_h, named_pipe, endpoint, operation | sort id.orig_h, id.resp_h, named_pipe, endpoint, operation | uniq -c

If present, top HTTP POST requests
method=POST | cut ts, uid, id, method, uri, status_code

Suricata

Alert Signature by severity and count
event_type=alert | count() by alert.severity,alert.signature | sort -r alert.severity, count

Severity 3 alert sigatures by destination with count
event_type=alert alert.severity=3 | count() by dest_ip, alert.signature | sort -r count
And Severity 2
event_type=alert alert.severity=2 | count() by dest_ip, alert.signature | sort -r count

Severity 3 alert signatures by source with count
event_type=alert alert.severity=3 | count() by src_ip, alert.signature | sort -r count
And Severity 2
event_type=alert alert.severity=2 | count() by src_ip, alert.signature | sort -r count

Top Alerts by Severity with dst, src, signature and count
event_type=alert |  cut src_ip, dest_ip,  alert.severity, alert.signature| sort -r alert.severity | uniq -c
