### ISSUE TITLE
Unable to load pcapng on Windows

### ISSUE THREAD

**Issue by LANopop** [brimsec/brim#510]
I just installed Brim on Windows 10 x64 and got the following error after loading a pcapng file.

```
Unable to generate full summary logs from PCAP 

Detail: zeek exited with status 1: warning in <command line>, line 7: problem initializing NB-DNS: no valid nameservers in resolver config fatal error in <command line>, line 7: problem with trace file - (bad dump file format) exit status 1
````

![image](https://user-images.githubusercontent.com/2630216/77416965-f171b500-6dc4-11ea-8f5e-94c2a5f24a55.png)

**Comment by philrz** [comment]
@LANopop: Thanks for the bug report. I've reproduced the issue here with another pcapng file, so we'll start looking into it.

For the benefit of our developers, here's the full error message in text when reproduced from the command line:

```
C:\Users\Phil\AppData\Local\Brim\app-0.5.1\resources\app\zdeps\zeek>.\zeek.exe -C -r non-overlap.pcapng local
warning: problem initializing NB-DNS: no valid nameservers in resolver config
fatal error: problem with trace file non-overlap.pcapng (bad dump file format)
exit status 1
```

Here's a pcapng that reproduces the problem:

[non-overlap.zip](https://github.com/brimsec/brim/files/4375752/non-overlap.zip)

**Comment by philrz** [comment]
For those seeking a workaround while we're putting together a fix, one approach is to convert from pcapng to regular pcap before bringing into the Brim app. For instance, with the example pcap linked here, I was able to do:

```
"\Program Files\Wireshark\mergecap.exe" -F pcap -w non-overlap.pcap non-overlap.pcapng
```

That file works in the app ok:

![image](https://user-images.githubusercontent.com/5934157/77462321-372c7e80-6dc1-11ea-909d-3d4840ce9ae9.png)

We'll still come up with the proper fix, though.

**Comment by philrz** [comment]
@LANopop: We've created a new release that supports pcapng. It's working in our tests, but please do give it a try and let me know if you're good now.

https://github.com/brimsec/brim/releases/tag/v0.5.3

This release is now also linked from the Downloads page on our website:

https://www.brimsecurity.com/download/

Thanks again for bringing this issue to our attention!
