### ISSUE TITLE
zqd binary not present

### ISSUE THREAD

**Issue by suricatalfon** [brimsec/brim#524]
Hello,

sudo npm install:

**(node:15643) UnhandledPromiseRejectionWarning: Error: zqd binary not present at /home/xxxx/install/brim/zdeps/zqd**

> Brim@0.5.4 build:css /home/alfon/install/brim
> node-sass-chokidar src/css --output dist/css "--watch" "--skip-initial"

(node:16754) UnhandledPromiseRejectionWarning: Error: zqd binary not present at /home/alfon/install/brim/zdeps/zqd
    at zqdCommand (/home/alfon/install/brim/dist/js/zqd/zqd.js:86:11)
    at ZQD.start (/home/alfon/install/brim/dist/js/zqd/zqd.js:123:44)
    at zqdMainHandler (/home/alfon/install/brim/dist/js/electron/ipc/zqd/mainHandler.js:12:9)
    at _callee$ (/home/alfon/install/brim/dist/js/electron/main.js:69:42)
    at tryCatch (/home/alfon/install/brim/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/home/alfon/install/brim/node_modules/regenerator-runtime/runtime.js:271:22)
    at Generator.prototype.<computed> [as next] (/home/alfon/install/brim/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/home/alfon/install/brim/dist/js/electron/main.js:33:103)
    at _next (/home/alfon/install/brim/dist/js/electron/main.js:35:194)
    at /home/alfon/install/brim/dist/js/electron/main.js:35:364
(node:16754) UnhandledPromiseRejectionWarning: Error: zqd binary not present at /home/alfon/install/brim/zdeps/zqd
    at zqdCommand (/home/alfon/install/brim/dist/js/zqd/zqd.js:86:11)
    at ZQD.start (/home/alfon/install/brim/dist/js/zqd/zqd.js:123:44)
    at zqdMainHandler (/home/alfon/install/brim/dist/js/electron/ipc/zqd/mainHandler.js:12:9)
    at _callee$ (/home/alfon/install/brim/dist/js/electron/main.js:69:42)
    at tryCatch (/home/alfon/install/brim/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/home/alfon/install/brim/node_modules/regenerator-runtime/runtime.js:271:22)
    at Generator.prototype.<computed> [as next] (/home/alfon/install/brim/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/home/alfon/install/brim/dist/js/electron/main.js:33:103)
    at _next (/home/alfon/install/brim/dist/js/electron/main.js:35:194)
    at /home/alfon/install/brim/dist/js/electron/main.js:35:364
(node:16754) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16754) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16754) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:16754) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Best regards,

**Comment by philrz** [comment]
@suricatalfon: Thanks for trying Brim & for the bug report.

After your report, I tried to reproduce the issue and that did lead us to quickly find & fix a problem that would have resulted in an error like you saw (https://github.com/brimsec/brim/pull/525). I can't say with 100% certainty that there's not another bug lurking in there, but could you try pulling the latest `master` of the Brim repo and attempt the `npm install` / `npm start` again?

If that doesn't fix it, it would help us to have a bit more info.

* First, what OS/version are you attempting this on? If it's Linux, please also provide the distro and version. Also please send the output of `node --version`.

* Next, I _think_ your debug output might have been truncated a bit, as the error you pasted is what I'd expect to see during the `npm start`, not the `npm install` as your paste implied. If you try with the latest `master` and it still doesn't work, could you send us the full output of `npm install` & `npm start`? If there's sensitive info in there that you don't feel comfortable including in a public issue like this one, you could email it to us at support@brimsecurity.com or you could [join our public Slack](https://join.slack.com/t/brimsec/shared_invite/zt-cy34xoxg-hZiTKUT~1KdGjlaBIuUUdg) and start a private 1-on-1 with me (I'm `@phil`) on there.

Hope to hear from you soon.

**Comment by suricatalfon** [comment]
Thanks  @philrz 

Here is all the information. The strange thing is that it has come to work for me. Not the next time.
(Sorry for my bad english).

**node --version**

v10.19.0

**Ubuntu 18.04.**

Linux 4.15.0-91-generic #92-Ubuntu SMP Fri Feb 28 11:09:48 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**sudo npm install**

> node-sass@4.13.1 install /home/xxx/install/brim/node_modules/node-sass
> node scripts/install.js

Cached binary found at /home/xxx/.npm/node-sass/4.13.1/linux-x64-64_binding.node

> electron-chromedriver@7.0.0 install /home/xxx/install/brim/node_modules/electron-chromedriver
> node ./download-chromedriver.js


> core-js@3.6.2 postinstall /home/xxx/install/brim/node_modules/@babel/node/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> core-js@2.6.11 postinstall /home/xxx/install/brim/node_modules/@babel/polyfill/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> core-js@3.6.2 postinstall /home/xxx/install/brim/node_modules/global-agent/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> node-sass@4.13.1 postinstall /home/xxx/install/brim/node_modules/node-sass
> node scripts/build.js

Binary found at /home/xxx/install/brim/node_modules/node-sass/vendor/linux-x64-64/binding.node
Testing binary
Binary is fine

> electron@7.1.9 postinstall /home/xxx/install/brim/node_modules/electron
> node install.js

npm WARN lifecycle Brim@0.5.4~postinstall: cannot run in wd Brim@0.5.4 node scripts/download-zdeps (wd=/home/xxx/install/brim)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: appdmg@0.6.0 (node_modules/appdmg):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for appdmg@0.6.0: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 1688 packages from 708 contributors and audited 898801 packages in 61.324s

37 packages are looking for funding
  run `npm fund` for details

found 895 vulnerabilities (871 low, 10 moderate, 14 high)
  run `npm audit fix` to fix them, or `npm audit` for details

**sudo npm audit fix**

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/livereload/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/livereload/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: appdmg@0.6.0 (node_modules/appdmg):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for appdmg@0.6.0: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: macos-alias@0.2.11 (node_modules/macos-alias):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for macos-alias@0.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ livereload@0.9.1
added 14 packages from 17 contributors, removed 5 packages and updated 15 packages in 22.36s

38 packages are looking for funding
  run `npm fund` for details

fixed 294 of 895 vulnerabilities in 898801 scanned packages
  49 vulnerabilities required manual review and could not be updated
  4 package updates for 552 vulnerabilities involved breaking changes
  (use `npm audit fix --force` to install breaking changes; or refer to `npm audit` for steps to fix these manually)

**npm start**

> Brim@0.5.4 start /home/xxx/install/brim
> npm-run-all -s clean build:* -p electron watch:*


> Brim@0.5.4 clean /home/xxx/install/brim
> node scripts/clean

Removed dist folder

> Brim@0.5.4 build:js /home/xxx/install/brim
> babel src/js -d dist/js --verbose

src/js/about.js -> dist/js/about.js
src/js/brim/ast.js -> dist/js/brim/ast.js
src/js/brim/ast.test.js -> dist/js/brim/ast.test.js
src/js/brim/brimTab.js -> dist/js/brim/brimTab.js
src/js/brim/compoundField.js -> dist/js/brim/compoundField.js
src/js/brim/dateTuple.js -> dist/js/brim/dateTuple.js
src/js/brim/entries.js -> dist/js/brim/entries.js
src/js/brim/entries.test.js -> dist/js/brim/entries.test.js
src/js/brim/field.js -> dist/js/brim/field.js
src/js/brim/field.test.js -> dist/js/brim/field.test.js
src/js/brim/flatRecordsBuffer/channel.js -> dist/js/brim/flatRecordsBuffer/channel.js
src/js/brim/flatRecordsBuffer/index.js -> dist/js/brim/flatRecordsBuffer/index.js
src/js/brim/flatRecordsBuffer/nestedRecord.js -> dist/js/brim/flatRecordsBuffer/nestedRecord.js
src/js/brim/flatRecordsBuffer/test.js -> dist/js/brim/flatRecordsBuffer/test.js
src/js/brim/flatRecordsBuffer/zngToZeekTypes.js -> dist/js/brim/flatRecordsBuffer/zngToZeekTypes.js
src/js/brim/flatRecordsBuffer/zngToZeekTypes.test.js -> dist/js/brim/flatRecordsBuffer/zngToZeekTypes.test.js
src/js/brim/index.js -> dist/js/brim/index.js
src/js/brim/interop.js -> dist/js/brim/interop.js
src/js/brim/log.js -> dist/js/brim/log.js
src/js/brim/program.js -> dist/js/brim/program.js
src/js/brim/program.test.js -> dist/js/brim/program.test.js
src/js/brim/randomHash.js -> dist/js/brim/randomHash.js
src/js/brim/record.js -> dist/js/brim/record.js
src/js/brim/relTime.js -> dist/js/brim/relTime.js
src/js/brim/relTime.test.js -> dist/js/brim/relTime.test.js
src/js/brim/search.js -> dist/js/brim/search.js
src/js/brim/space.js -> dist/js/brim/space.js
src/js/brim/space.test.js -> dist/js/brim/space.test.js
src/js/brim/span.js -> dist/js/brim/span.js
src/js/brim/span.test.js -> dist/js/brim/span.test.js
src/js/brim/syntax.js -> dist/js/brim/syntax.js
src/js/brim/table.js -> dist/js/brim/table.js
src/js/brim/time.js -> dist/js/brim/time.js
src/js/brim/time.test.js -> dist/js/brim/time.test.js
src/js/brim/zeekLogInfo.js -> dist/js/brim/zeekLogInfo.js
src/js/components/AboutModal.js -> dist/js/components/AboutModal.js
src/js/components/AboutWindow.js -> dist/js/components/AboutWindow.js
src/js/components/Animate.js -> dist/js/components/Animate.js
src/js/components/AnimateChildren.js -> dist/js/components/AnimateChildren.js
src/js/components/App.js -> dist/js/components/App.js
src/js/components/AppErrorBoundary.js -> dist/js/components/AppErrorBoundary.js
src/js/components/BrimTextLogo.js -> dist/js/components/BrimTextLogo.js
src/js/components/ButtonRow.js -> dist/js/components/ButtonRow.js
src/js/components/Buttons.js -> dist/js/components/Buttons.js
src/js/components/CircleChevron.js -> dist/js/components/CircleChevron.js
src/js/components/CloseButton.js -> dist/js/components/CloseButton.js
src/js/components/ClusterPicker.js -> dist/js/components/ClusterPicker.js
src/js/components/ColumnChooser.js -> dist/js/components/ColumnChooser.js
src/js/components/ColumnChooserMenu.js -> dist/js/components/ColumnChooserMenu.js
src/js/components/ConnVersation.js -> dist/js/components/ConnVersation.js
src/js/components/ControlBar.js -> dist/js/components/ControlBar.js
src/js/components/CurlModal.js -> dist/js/components/CurlModal.js
src/js/components/DebugModal.js -> dist/js/components/DebugModal.js
src/js/components/DimPortal.js -> dist/js/components/DimPortal.js
src/js/components/Dimens.js -> dist/js/components/Dimens.js
src/js/components/DownloadProgress.js -> dist/js/components/DownloadProgress.js
src/js/components/DragAnchor.js -> dist/js/components/DragAnchor.js
src/js/components/DropMenu.js -> dist/js/components/DropMenu.js
src/js/components/EmptyCheck.js -> dist/js/components/EmptyCheck.js
src/js/components/EmptyMessage.js -> dist/js/components/EmptyMessage.js
src/js/components/EmptySpaceModal.js -> dist/js/components/EmptySpaceModal.js
src/js/components/ErrorNotice.js -> dist/js/components/ErrorNotice.js
src/js/components/FieldCell.js -> dist/js/components/FieldCell.js
src/js/components/FilterNode.js -> dist/js/components/FilterNode.js
src/js/components/FilterTree/helpers.js -> dist/js/components/FilterTree/helpers.js
src/js/components/FilterTree/helpers.test.js -> dist/js/components/FilterTree/helpers.test.js
src/js/components/FilterTree.js -> dist/js/components/FilterTree.js
src/js/components/HistogramTooltip.js -> dist/js/components/HistogramTooltip.js
src/js/components/HistoryStepper.js -> dist/js/components/HistoryStepper.js
src/js/components/InlineTableLoading.js -> dist/js/components/InlineTableLoading.js
src/js/components/Investigation/FindingCard.js -> dist/js/components/Investigation/FindingCard.js
src/js/components/Investigation/FindingProgram.js -> dist/js/components/Investigation/FindingProgram.js
src/js/components/Investigation/InvestigationLinear.js -> dist/js/components/Investigation/InvestigationLinear.js
src/js/components/Investigation/useFindings.js -> dist/js/components/Investigation/useFindings.js
src/js/components/LatestError.js ->

ds.js
src/js/services/zealot/defaults.js -> dist/js/services/zealot/defaults.js
src/js/services/zealot/fetcher.js -> dist/js/services/zealot/fetcher.js
src/js/services/zealot/index.js -> dist/js/services/zealot/index.js
src/js/services/zealot/jsonPipeIterator.js -> dist/js/services/zealot/jsonPipeIterator.js
src/js/services/zealot/pcapsApi.js -> dist/js/services/zealot/pcapsApi.js
src/js/services/zealot/searchApi.js -> dist/js/services/zealot/searchApi.js
src/js/services/zealot/spacesApi.js -> dist/js/services/zealot/spacesApi.js
src/js/services/zealot/test.js -> dist/js/services/zealot/test.js
src/js/services/zealot/textIterator.js -> dist/js/services/zealot/textIterator.js
src/js/services/zealot/types.js -> dist/js/services/zealot/types.js
src/js/services/zealot/utils.js -> dist/js/services/zealot/utils.js
src/js/services/zeekLogDescriptions.js -> dist/js/services/zeekLogDescriptions.js
src/js/state/Boomd/actions.js -> dist/js/state/Boomd/actions.js
src/js/state/Boomd/flows.js -> dist/js/state/Boomd/flows.js
src/js/state/Boomd/index.js -> dist/js/state/Boomd/index.js
src/js/state/Boomd/reducer.js -> dist/js/state/Boomd/reducer.js
src/js/state/Boomd/selectors.js -> dist/js/state/Boomd/selectors.js
src/js/state/Boomd/test.js -> dist/js/state/Boomd/test.js
src/js/state/Boomd/types.js -> dist/js/state/Boomd/types.js
src/js/state/Chart/actions.js -> dist/js/state/Chart/actions.js
src/js/state/Chart/index.js -> dist/js/state/Chart/index.js
src/js/state/Chart/reducer.js -> dist/js/state/Chart/reducer.js
src/js/state/Chart/selectors.js -> dist/js/state/Chart/selectors.js
src/js/state/Chart/test.js -> dist/js/state/Chart/test.js
src/js/state/Chart/types.js -> dist/js/state/Chart/types.js
src/js/state/Clusters/actions.js -> dist/js/state/Clusters/actions.js
src/js/state/Clusters/flows.js -> dist/js/state/Clusters/flows.js
src/js/state/Clusters/index.js -> dist/js/state/Clusters/index.js
src/js/state/Clusters/reducer.js -> dist/js/state/Clusters/reducer.js
src/js/state/Clusters/selectors.js -> dist/js/state/Clusters/selectors.js
src/js/state/Clusters/test.js -> dist/js/state/Clusters/test.js
src/js/state/Clusters/types.js -> dist/js/state/Clusters/types.js
src/js/state/Columns/actions.js -> dist/js/state/Columns/actions.js
src/js/state/Columns/index.js -> dist/js/state/Columns/index.js
src/js/state/Columns/reducer.js -> dist/js/state/Columns/reducer.js
src/js/state/Columns/selectors.js -> dist/js/state/Columns/selectors.js
src/js/state/Columns/test.js -> dist/js/state/Columns/test.js
src/js/state/Columns/types.js -> dist/js/state/Columns/types.js
src/js/state/Errors/actions.js -> dist/js/state/Errors/actions.js
src/js/state/Errors/index.js -> dist/js/state/Errors/index.js
src/js/state/Errors/reducer.js -> dist/js/state/Errors/reducer.js
src/js/state/Errors/selectors.js -> dist/js/state/Errors/selectors.js
src/js/state/Errors/test.js -> dist/js/state/Errors/test.js
src/js/state/Errors/types.js -> dist/js/state/Errors/types.js
src/js/state/GlobalContext.js -> dist/js/state/GlobalContext.js
src/js/state/Handlers/actions.js -> dist/js/state/Handlers/actions.js
src/js/state/Handlers/index.js -> dist/js/state/Handlers/index.js
src/js/state/Handlers/reducer.js -> dist/js/state/Handlers/reducer.js
src/js/state/Handlers/selectors.js -> dist/js/state/Handlers/selectors.js
src/js/state/Handlers/types.js -> dist/js/state/Handlers/types.js
src/js/state/History/actions.js -> dist/js/state/History/actions.js
src/js/state/History/index.js -> dist/js/state/History/index.js
src/js/state/History/reducer.js -> dist/js/state/History/reducer.js
src/js/state/History/selectors.js -> dist/js/state/History/selectors.js
src/js/state/History/test.js -> dist/js/state/History/test.js
src/js/state/History/types.js -> dist/js/state/History/types.js
src/js/state/Investigation/actions.js -> dist/js/state/Investigation/actions.js
src/js/state/Investigation/index.js -> dist/js/state/Investigation/index.js
src/js/state/Investigation/reducer.js -> dist/js/state/Investigation/reducer.js
src/js/state/Investigation/selectors.js -> dist/js/state/Investigation/selectors.js
src/js/state/Investigation/test.js -> dist/js/state/Investigation/test.js
src/js/state/Investigation/types.js -> dist/js/state/Investigation/types.js
src/js/state/LogDetails/actions.js -> dist/js/state/LogDetails/actions.js
src/js/state/LogDetails/index.js -> dist/js/state/LogDetails/index.js
src/js/state/LogDetails/reducer.js -> dist/js/state/LogDetails/reducer.js
src/js/state/LogDetails/selectors.js -> dist/js/state/LogDetails/selectors.js
src/js/state/LogDetails/test.js -> dist/js/state/LogDetails/test.js
src/js/state/LogDetails/types.js -> dist/js/state/LogDetails/types.js
src/js/state/Modal/actions.js -> dist/js/state/Modal/actions.js
src/js/state/Modal/index.js -> dist/js/state/Modal/index.js
src/js/state/Modal/reducer.js -> dist/js/state/Modal/reducer.js
src/js/state/Modal/selectors.js -> dist/js/state/Modal/selectors.js
src/js/state/Modal/test.js -> dist/js/state/Modal/test.js
src/js/state/Modal/types.js -> dist/js/state/Modal/types.js
src/js/state/Notice/actions.js -> dist/js/state/Notice/actions.js
src/js/state/Notice/flows.js -> dist/js/state/Notice/flows.js
src/js/state/Notice/index.js -> dist/js/state/Notice/index.js
src/js/state/Notice/reducer.js -> dist/js/state/Notice/reducer.js
src/js/state/Notice/selectors.js -> dist/js/state/Notice/selectors.js
src/js/state/Notice/test.js -> dist/js/state/Notice/test.js
src/js/state/Notice/types.js -> dist/js/state/Notice/types.js
src/js/state/Packets/actions.js -> dist/js/state/Packets/actions.js
src/js/state/Packets/flows.js -> dist/js/state/Packets/flows.js
src/js/state/Packets/index.js -> dist/js/state/Packets/index.js
src/js/state/Packets/reducer.js -> dist/js/state/Packets/reducer.js
src/js/state/Packets/selectors.js -> dist/js/state/Packets/selectors.js
src/js/state/Packets/test.js -> dist/js/state/Packets/test.js
src/js/state/Packets/types.js -> dist/js/state/Packets/types.js
src/js/state/Search/actions.js -> dist/js/state/Search/actions.js
src/js/state/Search/flows.js -> dist/js/state/Search/flows.js
src/js/state/Search/index.js -> dist/js/state/Search/index.js
src/js/state/Search/reducer.js -> dist/js/state/Search/reducer.js
src/js/state/Search/selectors.js -> dist/js/state/Search/selectors.js
src/js/state/Search/test.js -> dist/js/state/Search/test.js
src/js/state/Search/types.js -> dist/js/state/Search/types.js
src/js/state/SearchBar/actions.js -> dist/js/state/SearchBar/actions.js
src/js/state/SearchBar/flows.js -> dist/js/state/SearchBar/flows.js
src/js/state/SearchBar/index.js -> dist/js/state/SearchBar/index.js
src/js/state/SearchBar/reducer.js -> dist/js/state/SearchBar/reducer.js
src/js/state/SearchBar/selectors.js -> dist/js/state/SearchBar/selectors.js
src/js/state/SearchBar/test.js -> dist/js/state/SearchBar/test.js
src/js/state/SearchBar/types.js -> dist/js/state/SearchBar/types.js
src/js/state/Spaces/actions.js -> dist/js/state/Spaces/actions.js
src/js/state/Spaces/index.js -> dist/js/state/Spaces/index.js
src/js/state/Spaces/reducer.js -> dist/js/state/Spaces/reducer.js
src/js/state/Spaces/selectors.js -> dist/js/state/Spaces/selectors.js
src/js/state/Spaces/test.js -> dist/js/state/Spaces/test.js
src/js/state/Spaces/types.js -> dist/js/state/Spaces/types.js
src/js/state/Tab/activeTabSelect.js -> dist/js/state/Tab/activeTabSelect.js
src/js/state/Tab/flows.js -> dist/js/state/Tab/flows.js
src/js/state/Tab/index.js -> dist/js/state/Tab/index.js
src/js/state/Tab/reducer.js -> dist/js/state/Tab/reducer.js
src/js/state/Tab/selectors.js -> dist/js/state/Tab/selectors.js
src/js/state/Tab/types.js -> dist/js/state/Tab/types.js
src/js/state/Tabs/actions.js -> dist/js/state/Tabs/actions.js
src/js/state/Tabs/flows.js -> dist/js/state/Tabs/flows.js
src/js/state/Tabs/index.js -> dist/js/state/Tabs/index.js
src/js/state/Tabs/reducer.js -> dist/js/state/Tabs/reducer.js
src/js/state/Tabs/selectors.js -> dist/js/state/Tabs/selectors.js
src/js/state/Tabs/test.js -> dist/js/state/Tabs/test.js
src/js/state/Tabs/types.js -> dist/js/state/Tabs/types.js
src/js/state/View/actions.js -> dist/js/state/View/actions.js
src/js/state/View/index.js -> dist/js/state/View/index.js
src/js/state/View/reducer.js -> dist/js/state/View/reducer.js
src/js/state/View/selectors.js -> dist/js/statther by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4025) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4025) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:4025) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.e/View/selectors.js
src/js/state/View/test.js -> dist/js/state/View/test.js
src/js/state/View/types.js -> dist/js/state/View/types.js
src/js/state/Viewer/actions.js -> dist/js/state/Viewer/actions.js
src/js/state/Viewer/hashDescriptorKeys.js -> dist/js/state/Viewer/hashDescriptorKeys.js
src/js/state/Viewer/index.js -> dist/js/state/Viewer/index.js
src/js/state/Viewer/reducer.js -> dist/js/state/Viewer/reducer.js
src/js/state/Viewer/selectors.js -> dist/js/state/Viewer/selectors.js
src/js/state/Viewer/test.js -> dist/js/state/Viewer/test.js
src/js/state/Viewer/types.js -> dist/js/state/Viewer/types.js
src/js/state/createGlobalStore.js -> dist/js/state/createGlobalStore.js
src/js/state/globalReducer.js -> dist/js/state/globalReducer.js
src/js/state/isSerializable.js -> dist/js/state/isSerializable.js
src/js/state/rootReducer.js -> dist/js/state/rootReducer.js
src/js/state/types.js -> dist/js/state/types.js
src/js/stdlib/cmd.js -> dist/js/stdlib/cmd.js
src/js/stdlib/index.js -> dist/js/stdlib/index.js
src/js/stdlib/object.js -> dist/js/stdlib/object.js
src/js/stdlib/object.test.js -> dist/js/stdlib/other by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4025) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4025) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:4025) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.bject.test.js
src/js/test/MockBoomClient.js -> dist/js/test/MockBoomClient.js
src/js/test/dispatchAll.js -> dist/js/test/dispatchAll.js
src/js/test/fixtures/index.js -> dist/js/test/fixtures/index.js
src/js/test/globalSetup.js -> dist/js/test/globalSetup.js
src/js/test/helpers/loginTo.js -> dist/js/test/helpers/loginTo.js
src/js/test/helpers/provide.js -> dist/js/test/helpers/provide.js
src/js/test/initTestStore.js -> dist/js/test/initTestStore.js
src/js/test/integration.js -> dist/js/test/integration.js
src/js/test/mockLogs.js -> dist/js/test/mockLogs.js
src/js/test/mockZealot.js -> dist/js/test/mockZealot.js
src/js/test/setup.js -> dist/js/test/setup.js
src/js/types/index.js -> dist/js/types/index.js
src/js/types/records.js -> dist/js/types/records.js
src/js/types/searches.js -> dist/js/types/searches.js
src/js/zeekLogInfo.test.js -> dist/js/zeekLogInfo.test.js
src/js/zqd/zqd.js -> dist/js/zqd/zqd.js
Successfully compiled 548 files with Babel.

> Brim@0.5.4 build:css /home/xxx/install/brim
> node-sass-chokidar src/css --output dist/css

Rendering Complete, saving .css file...
Wrote CSS to /home/xxx/install/brim/dist/css/main.css
Wrote 1 CSS files to /home/xxx/install/brim/dist/css

> Brim@0.5.4 build:static /home/xxx/install/brim
> cpx "src/static/**" dist/static


> Brim@0.5.4 electron /home/xxx/install/brim
> electron .


> Brim@0.5.4 watch:reload /home/xxx/install/brim
> livereload dist


> Brim@0.5.4 watch:css /home/xxx/install/brim
> npm run build:css -- --watch --skip-initial


> Brim@0.5.4 watch:js /home/xxx/install/brim
> npm run build:js -- --watch --skip-initial-build


> Brim@0.5.4 watch:static /home/xxx/install/brim
> npm run build:static -- --watch

Starting LiveReload v0.9.1 for /home/xxx/install/brim/dist on port 35729.

> Brim@0.5.4 build:js /home/xxx/install/brim
> babel src/js -d dist/js --verbose "--watch" "--skip-initial-build"


> Brim@0.5.4 build:static /home/xxx/install/brim
> cpx "src/static/**" dist/static "--watch"


> Brim@0.5.4 build:css /home/xxx/install/brim
> node-sass-chokidar src/css --output dist/css "--watch" "--skip-initial"

(node:4025) UnhandledPromiseRejectionWarning: Error: zqd binary not present at /home/xxx/install/brim/zdeps/zqd
    at zqdCommand (/home/xxx/install/brim/dist/js/zqd/zqd.js:86:11)
    at ZQD.start (/home/xxx/install/brim/dist/js/zqd/zqd.js:123:44)
    at zqdMainHandler (/home/xxx/install/brim/dist/js/electron/ipc/zqd/mainHandler.js:12:9)
    at _callee$ (/home/xxx/install/brim/dist/js/electron/main.js:69:42)
    at tryCatch (/home/xxx/install/brim/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/home/xxx/install/brim/node_modules/regenerator-runtime/runtime.js:271:22)
    at Generator.prototype.<computed> [as next] (/home/xxx/install/brim/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/home/xxx/install/brim/dist/js/electron/main.js:33:103)
    at _next (/home/xxx/install/brim/dist/js/electron/main.js:35:194)
    at /home/xxx/install/brim/dist/js/electron/main.js:35:364
(node:4025) UnhandledPromiseRejectionWarning: Error: zqd binary not present at /home/xxx/install/brim/zdeps/zqd
    at zqdCommand (/home/xxx/install/brim/dist/js/zqd/zqd.js:86:11)
    at ZQD.start (/home/xxx/install/brim/dist/js/zqd/zqd.js:123:44)
    at zqdMainHandler (/home/xxx/install/brim/dist/js/electron/ipc/zqd/mainHandler.js:12:9)
    at _callee$ (/home/xxx/install/brim/dist/js/electron/main.js:69:42)
    at tryCatch (/home/xxx/install/brim/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/home/xxx/install/brim/node_modules/regenerator-runtime/runtime.js:271:22)
    at Generator.prototype.<computed> [as next] (/home/xxx/install/brim/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/home/xxx/install/brim/dist/js/electron/main.js:33:103)
    at _next (/home/xxx/install/brim/dist/js/electron/main.js:35:194)
    at /home/xxx/install/brim/dist/js/electron/main.js:35:364
(node:4025) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4025) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4025) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:4025) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


Best regards,

**Comment by philrz** [comment]
Thanks for the update @suricatalfon. I'll go ahead and close this one then.
