### ISSUE TITLE
Ensure Brim user can find ZQL docs

### ISSUE THREAD

**Issue by philrz** [brimsec/brim#529]
A user made the suggestion on Slack:
> oh yeah, you guys should have a link to the query syntax somewhere in the brim app
i wasn't sure what i could type into the search box

I'd been thinking users would have come to the app after having sat through the [demo video](https://www.youtube.com/channel/UC0ju7Esmh13oLS8FTS-B3Eg) and heard about the dependency on zq/ZQL, the pointers to the repos with the language docs, etc. But the user's experience is validation that not all will be that thorough/patient (duh!)

Can we add some kind of prominent link near the search box to https://github.com/brimsec/zq/tree/master/zql/docs?

Adding also the link to query language as a new list item in the Help area is useful. 

![help2.jpg](https://images.zenhubusercontent.com/5e8b7dd61f02b3461f7761d3/c54ce91e-1c07-47fb-8972-c2c9ce337ffa)

**Comment by siskojr** [comment]
I got similar queries by two more users. 

Adding request to included in help section as part of @philrz description for completeness.

For reference as a familiar method for users, Wireshark provides help on the filter with a right-click action in the search pane
![image.png](https://images.zenhubusercontent.com/5e8b7dd61f02b3461f7761d3/2f20439b-3817-4511-8463-3356145277d0)

**Comment by philrz** [comment]
Verified in Brim commit `93ffb60`. Per the attached video, the ZQL docs are now available via **Help > Query Syntax Docs**.

[Verify.mov.zip](https://github.com/brimsec/brim/files/4954578/Verify.mov.zip)

Thanks @r-franke!
