### ISSUE TITLE
Show "Whole Space" by default when sensible, or a reasonable maximum otherwise

### ISSUE THREAD

**Issue by philrz** [brimsec/brim#531]
Background: In Brim v0 where the user workflow always starts with a pcap, we learn the start/end times of the pcap as we're indexing it and use them to set the initial time span of the Space while the pcap is still ingesting. This way the histogram time range is consistently at the whole time range throughout ingest and fills in with more bars as the screen is refreshed.

 In v1 when we'll let users bring in Zeek logs without pcaps, we won't have that guidance from the pcap anymore. Also, there's concern that always setting the time span to cover 100% of the ingested data might make queries frustratingly slow, so it might make sense to select a default time range that covers a substantial amount of data, but not necessarily everything.

@mccanne had a proposal:
> The app could fetch timespan of  space GET then  bucket time into say 1000 buckets (i.e., delta = (maxTs - minTs) / 1000)), then run a `* | every $delta count()`.  Now we know the density of events and we can choose the largest default time window (rounded to something sensible 1 min, 15 min, 1 hour, 1 day, etc) such that the default window is the largest window containing not more than say 1 million events.  This would be especially useful UX once we have a time index on the bzng file things only get slow when you zoom out to the whole space as opposed to starting slow from the start.

**Comment by jameskerr** [comment]
To me this seems confusing to have a different default amount of time selected in the time span for each set of logs that I open with Brim. 

I would propose we close this issue and keep the current behavior where we select the whole space. It's been a month since we opened this issue and I wanted to ensure this still made sense.

**Comment by siskojr** [comment]
At an internal meeting we decided to keep current implementation. If we hear requests from users to change the behavior, we will consider providing different options, like "last X minutes" to help with slow queries.

As of v0.9.1, the Whole Space for Zeek log ingest also represents the right time span and histogram.

Same data set imported from pcap and from logs shows same results.
1. From .pcap:
![image](https://user-images.githubusercontent.com/3593904/81757749-c1659a80-9474-11ea-9fc6-e02f7f0e4591.png)

2. From logs:
![image](https://user-images.githubusercontent.com/3593904/81757786-db06e200-9474-11ea-9523-9dca49ba0cad.png)
