### ISSUE TITLE
Close/reopen laptop lid - Brim shows Network error

### ISSUE THREAD

**Issue by philrz** [brimsec/brim#533]
This can be considered low priority, as it does not always happen. It's hard to reproduce and may be related to the size of ingested pcaps. Here's a screenshot of one time the problem reproduced:

![image](https://user-images.githubusercontent.com/5934157/78170308-9c0e5700-7407-11ea-9625-57b2f724b8ba.png)

More detail from the user who originally reported it:

> When this happened, the ingest process stopped and I had to open file again and start over. I found the same problem when the screen saving/automatic lock of account happened.

**Comment by siskojr** [comment]
I have tested this issue again with v0.5.4 and still happens. 
I can easily reproduce now as follows.

1) Open big pcap file. 
2) processing packets and progress bar
3) close lid and open again.


The errors I get looking at it with Developer tools are: 
1. Failed to load resource: the server responded with a status of 400 (Bad Request)
2. Failed to load resource: net::ERR_NETWORK_IO_SUSPENDED
3. /Applications/Brim.app/Contents/Resources/app/dist/js/services/zealot/fetcher.js:218 POST http://localhost:9867/space/wrc12x.pcap.brim/packet net::ERR_NETWORK_IO_SUSPENDED 202 (Accepted)


<img width="1075" alt="image" src="https://user-images.githubusercontent.com/3593904/78223813-5b9cf080-747c-11ea-8213-286e8764a61f.png">

I can see how the zeek process does not show in the system after this error.

**Comment by philrz** [comment]
Scope of this has been narrowed to simply improve the error message.

**Comment by siskojr** [comment]
Good call. 
I could reproduce if inactivity timer kicked in during an ingest.
But as a user installed the tool amphetamine ‎Amphetamine on the Mac App Store
https://apps.apple.com › app › amphetamine so that issue did not happen. 

Thanks

**Comment by philrz** [comment]
Verified in Brim commit `8f8df0c` talking to `zqd` commit `335d284`. Following the original repro instructions, I closed the lid of my laptop during pcap import and it triggered the new error message.

![image](https://user-images.githubusercontent.com/5934157/81073916-2b8ea600-8e9d-11ea-9411-67cc13b9995c.png)

Thanks @jameskerr!
