### ISSUE TITLE
Agree on contract for "reset state" for tests

### ISSUE THREAD

**Issue by philrz** [brimsec/brim#546]
@mikesbrown says:

---
Tests need to be able to set themselves up. The "Reset State" mechanism supported by Brim is a pretty convenient way to get to a "good-enough" initial state for tests.

"Reset State" has shown to be buggy in the past (see PROD-515 and PROD-539 for examples).

For both these reasons, integration tests made extensive use of "Reset State": both as a setup step, and also in a specific test in which the app was "dirtied" with state and minimally verified to be reset.

When @alfred-landrum was working on https://github.com/brimsec/brim/pull/452 , he reported that the mechanism we use for resetting state in integration tests was causing his test to fail, and he commented it out. While I could not reproduce it locally, indeed, https://www.electronjs.org/docs/api/web-contents#contentssendchannel-args confirms this is asynchronous.

While reviewing how "reset state" works, I was also reminded that the integration test's "reset state" is not a "full reset state".

The integration tests send "resetState" to the renderer process through the webcontents that spectron makes available. The code for handling a resetState sent to the render process is here:

https://github.com/brimsec/brim/blob/d468eeeda55187a108fea51c0aab5a8e689e7952/src/js/initializers/initShortcuts.js#L36

```
ipcRenderer.on("resetState", () => {
    clearState()
    location.reload()
  })
```

But the menu-driven reset state, which we don't have access to in integration tests, sends "resetState" to the renderer AND removes a file. That code is here:

https://github.com/brimsec/brim/blob/d468eeeda55187a108fea51c0aab5a8e689e7952/src/js/electron/menu/searchAppMenu.js#L96

```
{
          label: "Reset State",
          click: () => {
            send("resetState")
            lib
              .file(config.windowStateFile())
              .remove()
              .catch(() => {})
          }
        }
```

I'm mentioning all this stuff because the asynchronous nature of `webcontents.send("resetState")` needs to be dealt with, but at the same time, we should come up with a contract for how integration tests will reset state.

1. Ideally the test could do something like `webcontents.sendSync()`, but I can't find its equivalent at https://www.electronjs.org/docs/api/web-contents . Absent that, I'd be happy for ideas here. A strawman absent of something better is to have something in the DOM that reports a timestamp in unix seconds of when state was last "set". The test can get that element, issue resetState, and wait for that element's value to increase.

2. Ideally the test would simulate the "full reset state" that includes the deletion of `config.windowStateFile()` through the app. How this is done sort of depends on 1. For example, if it's possible to move the deletion of the state file to the renderer process, then this problem goes away. If it can't, should we punt on that and make the test responsible for deleting the state file?

These almost certainly require a change to Brim. cc: @jameskerr and @mason-fish. And while this doesn't seem like a feature need for brim-v0, it's important in order to facilitate stable integration testing.

UPDATE:

Messing with https://github.com/brimsec/brim/pull/452 locally has caused me to go down a state persistence rabbit hole. Here's an update. I was testing it locally and noticed on subsequent runs, we were always being presented with the "Open PCAPs" screen. This is odd because the old behavior of integration tests with boomd would present you with "wherever you had been before". The state I expected to see upon running an integration test that ingests PCAPs is that to run it a second time, the same PCAP file was already ingested, unless you "reset state", which I had pointed out @alfred-landrum  had already disabled. Instead, state appeared to be reset even without a "reset state" call by the test. This was bugging the hell out of me.

When I run the app using Spectron, Electron’s `app.getPath(“userData”)` is not the OS X `~/Library/Application Support/Brim`. Instead, for each test, it’s a temp directory, such as `/var/folders/x9/b_56b0s947b58yxjgdktg1th0000gn/T/.org.chromium.Chromium.A9chgr`. This must have to do with Spectron and Chromedriver. I'm able to work around this passing a user-data-dir value to Spectron's `chromeDriverArgs`. I have not yet been able to find why this differs. The docs I've found so far claim this is supposed to be a path resembling `~/Library/Application Support/Brim`.

This has important implications for tests. One is that tests by default won't be using the same userData path as the actual app. If we want to do so, I believe we'll have to do it ourselves, possibly reimplementing logic. This is a bit unfortunate: it's workable but the implications should be understood. It also makes the priority of a synchronous "reset state" lower. As long as we are OK paying the price to reingest PCAPs on any test that needs them, we can do nothing: state will be reset on every test anyway.

**Comment by mikesbrown** [comment]
Changes to the app have obviated the importance of this. It's not needed as a setup/cleanup step anymore. And when I want to reset state, I think I can just wait for state to look reset. I will reopen if this isn't the case.
