### ISSUE TITLE
Cleaner right-click tests and dealing with native menus

### ISSUE THREAD

**Issue by philrz** [brimsec/brim#554]
Native right-click menus present a problem for Spectron-based testing because the native menus aren't in the DOM. In brief, an out-of-band event listener receives intermediate representations of records, and desired actions.

It won't be easy to duplicate the exact solution we'd used in the past. Whereas before the "unit-of-test data" was static Zeek TSV, now it's PCAP. In the latter case, each test run will produce different UIDs. This means it won't be possible to have hard-coded intermediate representations of records, which worked well enough before. The UID will change each time.

(Ref: PROD-1489)

**Comment by mikesbrown** [comment]
Fixed by https://github.com/brimsec/brim/pull/749 !
