### ISSUE TITLE
Reassess end-to-end test strategy

### ISSUE THREAD

**Issue by philrz** [brimsec/brim#564]
@mikesbrown set the stage for this project with the description below. Implementation issues will ultimately be linked to this Epic.

---

The problem addressed by https://github.com/brimsec/brim/pull/561 is an example of an annoying feature of webdriver-based testing. Different environments yield different test bugs (not software functionality bugs). After a year, now is the time to reassess end to end testing.

Requirements:
* MUST work on Windows, Mac.
* MUST be able to test something written for Electron
* MUST be able to test an **installed** Electron app
* MUST have a mechanism for file upload

Nice to haves:
* Abstracts away waiting for element interaction (Cypress yes; TestCafe yes but less so; Spectron/Webdriver no)

There are claims Spectron can do all of the above, but with Spectron you get problems like the one addressed by https://github.com/brimsec/brim/pull/561.

There are some other options out there that fix some of these. Cypress and TestCafe are examples of end-to-end test frameworks that abstract away some of the element waiting/retrying we have to do when using Spectron/Webdriver. Cypress in particular looks like a pleasure to work with. https://docs.cypress.io/guides/getting-started/writing-your-first-test.html

The problem is that Cypress Electron support is in alpha, and the development for Electron support, while surging last August/September, seems to have stalled. Choosing Cypress is a bit risky then. TestCafe doesn't look as compelling as Cypress, but site docs imply better Electron support. Nevertheless on the side, I'm going to see what it's like trying to get our app to run in these.

Note there isn't much else for Electron apps that I've seen based on searches at https://discuss.atom.io/c/electron and https://www.reddit.com/r/electronjs/ . I will look at a few Electron app repos to see what else they might be using.

**Comment by mikesbrown** [comment]
A few updated points here:

1. #561 turned out not to be a Spectron problem.
2. Cypress Electron alpha support seems completely stalled
3. Spectron provides electron APIs, whose importance shouldn't be understated

I'm starting to feel like sticking with Spectron is the best way forward, and that there are still client and ZQ integration tests that could be written without going through the Brim app.

**Comment by mikesbrown** [comment]
Nothing really to be done here, though note once Electron is at 9 or higher Spectron 11.1 or higher can use Webdriver 6, presumably an improvement over Webdriver 4.
