### ISSUE TITLE
UX: errors during log ingest

### ISSUE THREAD

**Issue by siskojr** [brimsec/brim#568]
Provide a visual indication to the the user that the space he is looking at has ingest errors. ( the user may be looking at partial data). 

1. Show warning in the space area indicating there were errors during ingest. User can "clean/erase" this message.
2. Count the number of errors and show during ingest.
3. If user clicks on errors warning message, he will get details about the errors.

We will use the auto-detect logic of zq to figure out the format of zeek logs. We will try to ingest all we can, count errors and warn user that the space they are looking at does not have all the data. Providing details of the errors to the user will help him correct the problem or try to troubleshoot.

**Wireframe Error Warning**: showing warning to the user to indicate that the space he is looking at does not include all the data and contains ingest errors. 

![image.png](https://images.zenhubusercontent.com/5e8b7dd61f02b3461f7761d3/3ce87d7c-536e-466a-b764-bfe393e5e1ae)

If user hovers over the Warning icon, he can see details and also remove the warning message.
![image.png](https://images.zenhubusercontent.com/5e8b7dd61f02b3461f7761d3/bef6a09f-9015-46ba-b066-7ce4563a5290)

When ingesting,  progress bar will show movement. If errors are found, show a warning with number of errors. If user clicks on this warning message, provide error Details.  

![errors_ingest3.jpg](https://images.zenhubusercontent.com/5e8b7dd61f02b3461f7761d3/febc2241-8b10-4fce-8cb1-02e1a88ef8c6) 

This feature depends on backend improvements.

**Comment by henridf** [comment]
> This feature depends on backend improvements.

Specifically, https://github.com/brimsec/zq/issues/528

**Comment by philrz** [comment]
@alfred-landrum and I checked on the status of this one today, as lot of it _has_ been completed. As of Brim commit `f2b4948` talking to `zqd` commit `93b81f4`, the one thing that's not yet completed is:

> User can "clean/erase" this message.

Per the attached screenshot, I can click the warning icon that has the error count, view them, and dismiss the window via "Done". However there's no obvious control to clear them. Even quitting the app and coming back in, the warning icon and errors remain.

![image](https://user-images.githubusercontent.com/5934157/80776927-6ea4ee00-8b18-11ea-831b-01870208476e.png)

**Comment by jameskerr** [comment]
It's true, there is no way to clear them in the UI at this point. That's what this issue will be used for now.

**Comment by philrz** [comment]
Verified in Brim commit `670d3b8` talking to `zqd` commit `a09d0d6`. Per the attached video, now when I click the icon to open the warnings window, there's a "Clear Warnings" button I can hit to get rid of the warnings & the icon.

[Verify.zip](https://github.com/brimsec/brim/files/4566782/Verify.zip)

Thanks @jameskerr!
