### ISSUE TITLE
Profiling feature

### ISSUE THREAD

**Issue by lealog** [brimsec/brim#571]
Can you please evaluate if makes sense to add a "Profiling" feature? Wireshark has this feature - https://www.wireshark.org/docs/wsug_html_chunked/ChCustConfigProfilesSection.html.

This feature is really useful when you want to analyze different type of captures. For Wi-Fi(802.11), you have the Metageek profile - https://support.metageek.com/hc/en-us/articles/115013527388-Wireshark-Configuration-Profile

**Comment by siskojr** [comment]
We are closing this feature, there are other dependencies to be able to get 802.11 support. 
We are working on a feature that will allow Logs to be tagged (and coloring rule could be part of it). 
A combination of this upcoming feature plua support of custom zeek scripts (with a user adding 802.11 WLAN zeek script) could provide similar functionality. 

As we add more functionality into Brim, the need for user profiles will surface and we will revisit this request at that time.

Thanks
