### ISSUE TITLE
Update design of open file area

### ISSUE THREAD

**Issue by jameskerr** [brimsec/brim#572]
Add the zeek Icon
Add the zeek to the accepted formats

**Comment by philrz** [comment]
Verified in Brim commit `870b60d7`.

The "Load Files" area now includes the Zeek icon and text listing Zeek as an accepted format.

![image](https://user-images.githubusercontent.com/5934157/80263223-cdfc8d00-8644-11ea-8b04-c87ce417e1dc.png)

I've also verified that the link to "Zeek ASCII/JSON" correctly leads to https://docs.zeek.org/en/current/scripts/base/frameworks/logging/writers/ascii.zeek.html.

Thanks @jameskerr!
