### ISSUE TITLE
Modal to display ingest errors

### ISSUE THREAD

**Issue by jameskerr** [brimsec/brim#577]
When the user clicks on the errors counter, we'll display a modal with a scrolling list of all the errors.

**Comment by philrz** [comment]
Verified in Brim commit `1fae48f`.

In the attached video, I drag in a log file that I know is going to generate a warning (a single JSON line `{"foo": "bar"}`). Brim now shows a message "Ingest failed with warnings" and a warning icon with a count. When clicked, it pops up a modal with the error detail, which in this case is the accurate message `/Users/phil/Desktop/ingest/foo.ndjson: line 1: missing path field`.

[Verify.zip](https://github.com/brimsec/brim/files/4533620/Verify.zip)

Thanks @jameskerr!
