### ISSUE TITLE
repeated key navigation for log detail locks up UI

### ISSUE THREAD

**Issue by alfred-landrum** [brimsec/brim#591]
If I open up a log details pane, then hold down the 'down' or 'up' keys, the UI locks up, and eventually all of the records briefly to display themselves at once in the pane. 
I saw this on macos and windows, using the latest master.

**Comment by philrz** [comment]
Re-opening. I just tried to verify this one in Brim commit `870b60d` (connecting to `zqd` commit `a4931cd`, FWIW), which includes the change in https://github.com/brimsec/brim/pull/670, and yet I was able to repro the issue using the original steps. I just ingested our common `all.pcap` test data, opened the Log Detail panel, clicked on the top event, and held down the Down arrow key. After just advancing through a few events, the app hung and did not respond to my clicks. As you can see in the attached video, after the perceived hang, I tried to resize the window and it did not redraw, as further evidence it was hung. It did eventually get unstuck by itself and I didn't measure how long that took with a stopwatch, but I just now did yet another repro and it has been hung for several minutes and is still stuck.

[Repro.mp4.zip](https://github.com/brimsec/brim/files/4532021/Repro.mp4.zip)

**Comment by mason-fish** [comment]
Thanks for catching that @philrz, turns out the last fix only addressed the network request throttling, but there was also a component rendering load that needs to be debounced as well. Just threw up a fix for that.

**Comment by philrz** [comment]
Verified in Brim commit `670d3b8` talking to `zqd` commit `a09d0d6`. Per the attached video, now I can hold down the arrow keys and it'll walk through the events without locking up the app.

[Verify.zip](https://github.com/brimsec/brim/files/4566774/Verify.zip)

Thanks @mason-fish!
