### ISSUE TITLE
Zeek Logs

### ISSUE THREAD

**Issue by zpravaiz** [brimsec/brim#617]
Hi,
This is a great tool I really enjoy using it. I would like to know what if I have only Zeek logs (no full cap). It would be nice to ingest these logs in Brim and have the same GUI and workflow for investigation. 
I would love to have this feature.

Regards

**Comment by henridf** [comment]
Hi @zpravaiz, thanks for the feedback and yes, we're already working on this.
It's tracked at #574 (and companion issues in the https://github.com/brimsec/zq repo).
