### ISSUE TITLE
Initial Linux release

### ISSUE THREAD

**Issue by alfred-landrum** [brimsec/brim#618]
We want to provide installable Linux releases of Brim. Our CI already builds and executes Linux based tests (using Ubuntu & xfvb). We have user reports about desired distros in #586 (note the comments there about flatpak.org) and a few other in the public #brim slack channel.

We currently use the Electron update service for autoupdates:
https://www.electronjs.org/docs/tutorial/updates

which does not support autoupdates on Linux. It will be acceptable if we don't initially support auto-update on Linux, but the user shouldn't see any errors or warnings about auto-update not working.

We need to:
- decide on the packaging format(s) that we want to provide. 
- add support for them in script/release as we do for other platforms
- add a CI trigger that will generate the release artifact & upload it as for other platforms
- add an icon and links to the Linux package(s) on the brimsecurity.com/download page.

**Comment by philrz** [comment]
Verified. I made `.deb` and `.rpm` release artifacts and installed them via double-click in the Files utilities of Ubuntu Desktop 18.04 and Fedora Workstation 31, respectively. Per the attached videos, in each I was able to drag a pcap into the app and open flows in Wireshark successfully.
