### ISSUE TITLE
brim dev build should depend on recent zq master tip

### ISSUE THREAD

**Issue by alfred-landrum** [brimsec/brim#634]
Brim's zq dependency should point to a recent zq master commit, so that running 'npm install' for development or integration tests will use recent zq code.

This should not be a "floating" dependency; that is, we shouldn't make the zq version in package.json something like "zq@master" that can change whenever it's evaluated. Instead, the zq dependency should always point to either a specific git commit or to a release tag.  

To do this, I think we would need to:
- add CI automation that updates the zq dependency in the Brim repo, whenever the zq repo's master moves.
- add support to zq's package.json so that it knows how to build the zq artifacts (zq, zqd, etc). 

The logic in Brim's download-zdeps should roughly stay the same: if the dependency is a semver tag (vX.X.X), then pull the zq artifacts from the Github release. Otherwise, it will need to build them, which implies that anyone developing on Brim would need to have go tooling available as well.

**Comment by henridf** [comment]
Sounds like the return of the zqbot ! 🙂

**Comment by mikesbrown** [comment]
The work here can be roughly divided into two parts.
1. Making zq at arbitrary commits npm-installable
2. Autoupdating 1.

I've made plans for the first and will work on that before planning out 2.

**Comment by mikesbrown** [comment]
Initial work is done. I'm going to leave this open for the time being to monitor update progress.
