### ISSUE TITLE
windows node cache slowing down CI

### ISSUE THREAD

**Issue by alfred-landrum** [brimsec/brim#641]
Looking at a long running Windows build, I noticed this in the npm cache action:

Cache Size: ~1485 MB (1557289122 B)

We tried to address this with https://github.com/brimsec/brim/pull/590 , and that definitely helped the macos builds.

**Comment by mikesbrown** [comment]
The problem was that on Windows, a 1.5G  NPM cache was already on disk before recalling our own cache. The logic to remove this extraneous cache wasn't working because `\` chars were quashed in the path. #646 fixes this.
