### ISSUE TITLE
windows: closing all windows but about window leaves brim unusable

### ISSUE THREAD

**Issue by alfred-landrum** [brimsec/brim#645]
On windows:
- click on 'About Brim' menu item to open the About window
- close any open search windows, leaving just the about window open
- now I'm stuck; I can't open new search windows (since we don't have an option to create a new search window from the taskbar)
- this is permanent:
  - if I close the about window, brim quits
  - but launching brim again will just bring up the about box, so I'm still stuck
  - uninstalling & reinstalling Brim doesn't help either

The only way to get out of this situation is to manually remove the <user>/AppData/Roaming/Brim/appState.json file.

**Comment by jameskerr** [comment]
I suggest that for this fix, we simply don't save the fact that the about window was opened. Closing and  re-opening brim will not restore the About window.

In addition to that, we'll want to add an action to the task bar to open a new window.

**Comment by philrz** [comment]
Verified in Brim commit `cc4e459` talking to `zqd` commit `335d284`.

Per the attached video & as described in the linked PR, now if I close everything but the About window, I can get back my search window by right-clicking the Brim icon in the Task Bar and selecting "New Window". Also, if I quit Brim with only the About window open, when I next launch Brim, it opens up with a fresh search window and no About window, hence not getting stuck like it did in the past.

[Verify.mov.zip](https://github.com/brimsec/brim/files/4578522/Verify.mov.zip)

Thanks @jameskerr!
