### ISSUE TITLE
adjust linux integration tests to use the deb package

### ISSUE THREAD

**Issue by alfred-landrum** [brimsec/brim#649]
The Linux integration tests should build and install the deb package, then run tests against that deployed image. We were able to do this with for the mac with some adjustments to the test:

https://github.com/brimsec/brim/blob/master/.github/workflows/ci.yml#L85
https://github.com/brimsec/brim/blob/master/itest/lib/app.js#L23
https://github.com/brimsec/brim/blob/master/itest/lib/app.js#L52

**Comment by mikesbrown** [comment]
This should be easy to do. I have a Linux VM (without a window manager). I was able to install the Debian package by doing this:
```sh
$ sudo apt -y install ./dist/installers/brim_amd64.deb
```
Then I applied this patch:
```diff
--- a/itest/lib/app.js
+++ b/itest/lib/app.js
@@ -23,7 +23,7 @@ const appStep = async (stepMessage, f) => {

 export const newAppInstance = (name: string, idx: number): Application => {
   const macInstallPath = "/Applications/Brim.app/Contents/MacOS/Brim"
-
+  const debianInstallPath = "/usr/bin/brim"
   // https://github.com/electron-userland/spectron#new-applicationoptions
   let appArgs = {
     startTimeout: 60000,
@@ -54,7 +54,8 @@ export const newAppInstance = (name: string, idx: number): Application => {
     appArgs = {...appArgs, path: macInstallPath}
     LOG.debug("Chose installed MacOS app location")
   } else {
-    appArgs = {...appArgs, path: electronPath, args: [repoDir()]}
+    //appArgs = {...appArgs, path: electronPath, args: [repoDir()]}
+    appArgs = {...appArgs, path: debianInstallPath}
     LOG.debug("Chose working copy app location")
   }
   return new Application(appArgs)
```
This test run then passed:
```sh
$ xvfb-run --auto-servernum -s "-screen 0 1280x1024x24" npm run itest -- -t tab itest/tests/smoke.test.js
```
While this test was running, I verified that we were running Brim out of `/usr/lib/brim`

**Comment by mikesbrown** [comment]
`sudo dpkg --force-depends -i ./dist/installers/brim_amd64.deb` should go faster and works on the same machine (with none of those deps installed).
