### ISSUE TITLE
Allow loading of GZIP'ed logs

### ISSUE THREAD

**Issue by philrz** [brimsec/brim#658]
Zeek's default log rotation behavior performs GZIP compression on log files as it moves them into date-stamped directories. As Brim starts to support direct loading of Zeek logs, it would be very handy for users if these could be loaded in that in that GZIP-compressed form rather than requiring the user to uncompress everything first.

While we're at it, it would surely be just as handy to accept GZIP-compressed pcaps as well, since these are often stored compressed to save disk space and reduce network transport time. The [wrccdc PCAPs](https://archive.wrccdc.org/pcaps/) that we often use for test data are one such example, but there's countless others out there.

**Comment by alfred-landrum** [comment]
Note: I'm separating out the compressed pcap ingest support into a separate zq issue: https://github.com/brimsec/zq/issues/671 .

**Comment by philrz** [comment]
Verified in Brim commit `f2b4948` talking to `zqd` commit `93b81f4`.

This got taken care of as a side-effect of the work done in #716. Since `zq` is already capable of loading GZIP'ed inputs, now that we're passing all non-pcap inputs on to `zqd`, this "just works" now. In the attached video we import a directory full of logs that came out of Zeek's log rotation, which always GZIPs them.

[Verify.zip](https://github.com/brimsec/brim/files/4564663/Verify.zip)

Thanks @jameskerr!
