### ISSUE TITLE
Failed ingest of Zeek logs leaves behind remnants of non-existent Space

### ISSUE THREAD

**Issue by philrz** [brimsec/brim#667]
Repro is in Brim commit `7bcd1801` talking to `zqd` commit `700f9ea`. In this case I tried to ingest the "year1" subset of the wrccdc data set and it failed due to the current 10-million event `sort` limit, which is fine. However, after the failure, the Space name was left behind in the "Recent Spaces" list and I could click on it and get a "No spaces in this cluster" message. Clicking to a new tab & back again showed everything clean as I'd expect, so it seems like there just needs to be a little additional cleanup.

See attached video:

[Repro.mp4.zip](https://github.com/brimsec/brim/files/4517656/Repro.mp4.zip)

**Comment by jameskerr** [comment]
This was fixed as a side effect of another issue going in. Here is the master branch working now. https://recordit.co/0tAu8KOZlF

**Comment by philrz** [comment]
Thanks for verifying @jameskerr!
