### ISSUE TITLE
Stop creating the .brim folder

### ISSUE THREAD

**Issue by alfred-landrum** [brimsec/brim#673]
We're going to stop creating the .brim folder next to ingested data, By default, we should *not* specify a data_dir in the space create api call; so the zng data & other space information will be created under zqd's `data/spaces` directory, under Electron's per-platform `userData` directory.

**Comment by philrz** [comment]
Verified in Brim commit `4be49d4` talking to `zqd` commit `335d284`. I made a release artifact and then ingested all four of the formats from [zq-sample-data](https://github.com/brimsec/zq-sample-data) as well as a pcap:

![image](https://user-images.githubusercontent.com/5934157/80999691-eebda300-8df9-11ea-86e8-84c00a8f03cb.png)

I then confirmed that the Space data no longer located adjacent to pcap nor in `$HOME/.brim`, but instead under Electron's per-platform `userData` directory, which on my Mac is:

```
$ tree "$HOME/Library/Application Support/Brim/data/spaces"
/Users/phil/Library/Application\ Support/Brim/data/spaces
├── hello.pcapng.brim
│   ├── all.zng
│   ├── config.json
│   ├── info.json
│   └── packets.idx.json
├── tzng.brim
│   ├── all.zng
│   ├── config.json
│   └── info.json
├── zeek-default.brim
│   ├── all.zng
│   ├── config.json
│   └── info.json
├── zeek-ndjson.brim
│   ├── all.zng
│   ├── config.json
│   └── info.json
└── zng.brim
    ├── all.zng
    ├── config.json
    └── info.json
```

Thanks @mason-fish!
