### ISSUE TITLE
brim: UI to rename a space

### ISSUE THREAD

**Issue by alfred-landrum** [brimsec/brim#674]
**Request**
As a user I want to change the space name so that I can have a naming structure similar to my preferences of file name organization.

**Description**
If a user ingests files in the following sequence:
…/day1/errors.pcap
…/day2/errors.pcap
the spaces that are created will have the following names:
errors.pcap.brim
errors.pcap.brim_01

The users may prefer to change the name to something more meaningful for them.

Provide the rename functionality with a right-click action in the Recent spaces pane.
![image.png](https://images.zenhubusercontent.com/5e8b7dd61f02b3461f7761d3/8009f05c-9ff9-4a2a-9bba-361bf7582069)

Desired: provide also the rename action directly in the tab name. Either right-click and rename or hit return key and allow rename like macOS functionality of file.
![image.png](https://images.zenhubusercontent.com/5e8b7dd61f02b3461f7761d3/f48f4662-e734-45de-86c5-32d604e17476)

**Comment by philrz** [comment]
Re-opening. Per the attached video, it seems this has mostly been addressed, but I've found a loose end. Testing with Brim commit `1969786`, I found that the rename is successful if I take the care to click the "Rename" button. However, as a user interacting with modals with a single button, I'm accustomed to being able to hit Enter and have it behave as if I'd clicked the button. In this case it instead closed the modal without performing the attempted rename. There's other places currently where hitting Enter saves the changes (e.g. in **Preferences** where the "Ok" is hit implicitly if I type something legit into one of the input boxes and hit enter), so I assume we'd want this to behave the same.

[Almost.zip](https://github.com/brimsec/brim/files/4685510/Almost.zip)

**Comment by siskojr** [comment]
Makes sense. Enter key is common.

**Comment by philrz** [comment]
Verified in Brim commit `16a82e1`. In the attached video, now I can also commit the rename by hitting Enter after I've typed the new name in the input box.

[Verify.mp4.zip](https://github.com/brimsec/brim/files/4703782/Verify.mp4.zip)

Thanks @mason-fish!
