### ISSUE TITLE
UI for zng file export

### ISSUE THREAD

**Issue by alfred-landrum** [brimsec/brim#677]
**Request**
As a User I want to be able to export the results of a query so that I can share or move the data from my analysis.

**Description**
Other tools like Wireshark or Caploader allow export or a selection of packets to disk.  In our case we want to provide similar functionality that will enable future transfer of information between desktop and server deployments.

This functionality will also allow cross-platform re-use of data, ZNG data, for example, linux to Windows.

Detailed requests:

1. Provide an export icon as part of the existing toolbar. This is a user friendly option.
2. Provide a menu option to export the query.
3. Provide a screen where the User can specify the filename and location to export.

Future functionality will allow Log tagging. Tagged logs could then be exported  to ZNG. Re-use of design is desired.

User flow:

1. The user performs an analysis that renders a query.
2. The user clicks the export icon (or query export option in menu) to export the results to disk.
3. The user specifies the location and name of the file. The type is predefined as ZNG.

Figure: Export icon as part of existing toolbar

![image.png](https://images.zenhubusercontent.com/5e8b7dd61f02b3461f7761d3/f5822c17-9871-47e0-97af-87596eadc98b)

Figure: Query section export option

![image.png](https://images.zenhubusercontent.com/5e8b7dd61f02b3461f7761d3/9070e2bb-0c7a-44bd-8e39-70cb994fff81)

Reference information, Wireshark export functionality.

1. Select packets
![image.png](https://images.zenhubusercontent.com/5e8b7dd61f02b3461f7761d3/634e4f99-0b68-401e-a8fb-6d95d5cc9a88)

2. Export
![image.png](https://images.zenhubusercontent.com/5e8b7dd61f02b3461f7761d3/5b0a2e1f-6134-48be-9ea9-179a37a82626)

3. Specify export parameters
![image.png](https://images.zenhubusercontent.com/5e8b7dd61f02b3461f7761d3/9fb16929-ee36-421a-824b-98a22e31501c)

Reference, Caploader implementation:
![image.png](https://images.zenhubusercontent.com/5e8b7dd61f02b3461f7761d3/ebd1cd86-c09a-43da-b392-15946a2b9bed)

**Comment by henridf** [comment]
@jameskerr @mason-fish: as of https://github.com/brimsec/zq/pull/743, the `/search` endpoint has a new `noctrl` query param, which signals that control messages (taskstart/taskend/stats) should not be sent.

so the query URL would be `/search?format=zng&noctrl=true`, with a `SearchRequest` body formatted as usual.

**Comment by jameskerr** [comment]
Excellent. Thanks @henridf

**Comment by philrz** [comment]
Verified in Brim commit `4edb45f` talking to `zqd` commit `3bd5700`.

In the attached video, I create a `count() by` table, export its results, and then view them in `zq` outside the app.

[Verify.mov.zip](https://github.com/brimsec/brim/files/4684243/Verify.mov.zip)

#814 lives on for the corner case of exporting limited columns when the user has narrowed down the set with the column picker.

Thanks @jameskerr!
