### ISSUE TITLE
Erasing Logs space includes message that will preserve original pcap file

### ISSUE THREAD

**Issue by siskojr** [brimsec/brim#686]
Requesting a change of text message to one that is neutral for both Log and pcap scenarios. Example: "This will delete the created .brim folder, but will preserve the original data."

A user who is familiar with Brim might probably understand, however using a text message that applies both to Log case and pcap case is clearer and more user friendly. 

Figure: the window message appearing when erasing space![image.png](https://images.zenhubusercontent.com/5e8b7dd61f02b3461f7761d3/b7e53a73-87f8-40e6-a67b-2da012fcc4ac)

**Comment by philrz** [comment]
Verified in Brim commit `e9b0840` talking to `zqd` tagged `v0.12.0`. Per the attached video, now regardless of whether the Space was generated by importing a pcap or Zeek logs, when it's deleted the user is given a generic "Are you sure you want to delete <space name>?" prompt.

Thanks @mason-fish!
