### ISSUE TITLE
Create base centos8 integration image

### ISSUE THREAD

**Issue by mattnibs** [brimsec/brim#701]
Currently we have to install these dependencies to run integration tests on .rpm build artifact:
```
dnf install -y xorg-x11-server-Xvfb git nss-tools pulseaudio
```

Let's create a base docker image that includes these dependencies and get rid of this step in ci.

**Comment by alfred-landrum** [comment]
@mattnibs : I think this was handled in brimsec/brim#684 , correct?

**Comment by mattnibs** [comment]
@alfred-landrum yep, closed
