### ISSUE TITLE
Include ZNG link as part of accepted formats

### ISSUE THREAD

**Issue by siskojr** [brimsec/brim#709]
**Request**
Include explicit mention of ZNG as supported format and provide a hyperlink to it's documentation page in GitHub.

**Rationale**
ZNG is Brim's native format, ideally suited for structured logs and designed for optimal search and analytics capabilities.

We want to highlight it's support and point users to the spec's documentation for education. 

Include a hyperlink as part of the Open File screen.
https://github.com/brimsec/zq/blob/master/zng/docs/README.md

![image.png](https://images.zenhubusercontent.com/5e8b7dd61f02b3461f7761d3/8b898b5b-de92-43b8-b30c-d7026a82ca55)

**Comment by philrz** [comment]
Closing this one as a duplicate, as the work to take care of this was ultimately tracked via #693.
