### ISSUE TITLE
Change Load file to Import file

### ISSUE THREAD

**Issue by siskojr** [brimsec/brim#711]
**Request**
Change the description in the App from current Load File to Import file

**Rationale**
The change will help communicate what really happens behind the scenes. The data space is independent of the files that the user is importing/dragging. If we remove the space we don't touch the original data. 

![image.png](https://images.zenhubusercontent.com/5e8b7dd61f02b3461f7761d3/d0e9737e-f22c-4d7d-9166-423d0e6b0a61)

**Comment by philrz** [comment]
Verified in Brim commit `7e0f417`. Per the attached video, the static text above the import box now says "IMPORT FILES", and when I start to drag a file icon over the import box, the text inside it changes to "DROP TO IMPORT..."

[Verify.zip](https://github.com/brimsec/brim/files/4566553/Verify.zip)

Thanks @mason-fish!
