### ISSUE TITLE
Date format - please support ISO 8601 

### ISSUE THREAD

**Issue by jedd** [brimsec/brim#733]
Greetings,

Great tool, but the 05/04/20 format is at odds with most other security tooling, which lets you pick a date format - eg the naturally sortable and non-ambiguous ISO 8601  (yyyy-mm-dd hh:mm:ss.xxx)

The above time in Australia (and quite a few other places) would likely be assumed to mean 5th April 2020 -- but brim shows that for 4th of May 2020.

**Comment by siskojr** [comment]
Hi @Jedd, 

Thanks for your suggestion. Makes sense, we are using the default format for a date in the US, and I know it is different in other countries, hence confusing. 

We will improve here. 
The time representation for the space is a bit more clear and I understand the format of the timestamp is the problem.


If you could join our slack channel would be more convenient to talk if you have more ideas for feature improvements, happy to consider them.

The link to join our slack: https://join.slack.com/t/brimsec/shared_invite/zt-cy34xoxg-hZiTKUT~1KdGjlaBIuUUdg

Appreciated.

Javier Rodriguez

Ref: ![image.png](https://images.zenhubusercontent.com/5e8b7dd61f02b3461f7761d3/d791f7f4-236e-4f3a-90a7-f8707b1089aa)

**Comment by philrz** [comment]
Verified in Brim commit `09559ee`. ISO 8601 timestamps are the new default:

![image](https://user-images.githubusercontent.com/5934157/81846369-d428af80-9506-11ea-957b-aa982d9f5f79.png)

The **Preferences** menu now also offers an option to change this default.

![image](https://user-images.githubusercontent.com/5934157/81846493-089c6b80-9507-11ea-8c42-af213fc8526e.png)

Plugging in the example format string `dddd, MMMM Do YYYY, h:mm:ss a` from the [doc](https://momentjs.com/docs/#/displaying/format/) that's linked from that **Preferences** page, I can see the modified format.

![image](https://user-images.githubusercontent.com/5934157/81846558-210c8600-9507-11ea-938f-8615560a4e69.png)

This functionality should go out in the next Brim release, which is expected to be tagged `v0.10.0` and is likely to go out within the next week.

Thanks @jameskerr!
