### ISSUE TITLE
UI preference for zeek runner

### ISSUE THREAD

**Issue by alfred-landrum** [brimsec/brim#741]
To support the bring-your-own-zeek effort, Brim will run zqd with a `-zeekrunner <path>` option, where the specified path should, by default, point to `zdeps/zeek/zeekrunner` (or zeekrunner.exe on windows).

We should have a UI preference that allows a user to override the path provided to the `-zeekrunner` argument. The preference should also provide a link to a wiki page (to be written) that documents how they can use this setting to customize how we generate zeek logs from pcaps.

**Comment by philrz** [comment]
Verified in Brim commit `718af8a` talking to `zqd` commit `8301413`.

In the attached video, I've already made the `zeekrunner` selection in **Preferences** and restarted Brim for the setting to take effect. I can see via `ps` that my `zeekrunner` selection is reflected in the `zqd` command line. In this case all I'd done was copy the "stock" `zeekrunner` script to the base directory of a customized Zeek v3.1.3 install to which I'd added the JA3 plugin. After importing a pcap, I click on an `ssl` event and confirm that the additional JA3 fields are present.

[Verify.zip](https://github.com/brimsec/brim/files/4629317/Verify.zip)

While working on this verification, I did stumble across new bug #777.

Thanks @jameskerr!
