### ISSUE TITLE
create byoz wiki page and link from prefs

### ISSUE THREAD

**Issue by alfred-landrum** [brimsec/brim#775]
In https://github.com/brimsec/brim/pull/771, we put a placeholder docs link for the zeek runner setting. That doc should point to a wiki page on the Brim repo that explains how a user could create their own zeek runner that would utilize their custom zeek setup.

**Comment by philrz** [comment]
Verified in Brim commit `416f14a`.

The wiki doc is at https://github.com/brimsec/brim/wiki/Zeek-Customization, and I've confirmed the link to it from the link next to the "Zeek Runner" preference leads there.

![image](https://user-images.githubusercontent.com/5934157/82105871-7d6fd100-96d2-11ea-9da2-83b0b3281b12.png)

Thanks @alfred-landrum!
