### ISSUE TITLE
Space not being deleted when quitting Brim during pcap import

### ISSUE THREAD

**Issue by philrz** [brimsec/brim#778]
Repro is with Brim commit `718af8a` talking to `zqd` commit `8301413`.

[Repro.mp4.zip](https://github.com/brimsec/brim/files/4629467/Repro.mp4.zip)

When I quit Brim, I can see the following message in my NPM window:

```
08:38:14.794 › [f5b7b022f0]:  Confirming Unload...
08:38:16.227 › [f5b7b022f0]:  Unloading
08:38:16.228 › [f5b7b022f0]:  starting delete for wrccdc.2018-03-24.101533000000000.pcap.brim
08:38:16.231 › [f5b7b022f0]:  Unable to delete space: wrccdc.2018-03-24.101533000000000.pcap.brim, reason: [object Object]
08:38:16.232 › [f5b7b022f0]:  Saving window state
08:38:16.654 › [f5b7b022f0]:  Window state saved
08:38:16.656 › [f5b7b022f0]:  Destroying window
```

**Comment by mattnibs** [comment]
Looks like the brim client is send the space name on the delete request. I did some sleuthing and it looks like Handlers state object just stores the spaceName and is using this to issue the delete request.

**Comment by philrz** [comment]
Verified in Brim commit `bbbb181` talking to `zqd` commit `8301413`. Per the attached video, now when I quit mid-pcap-import, the Space is deleted as expected, evidenced by the fact that when I restart the app I no longer see any remnants of a partially-imported leftover Space.

[Verify.zip](https://github.com/brimsec/brim/files/4631809/Verify.zip)

Thanks @jameskerr!
