### ISSUE TITLE
Provide foundational structure to the website so that we can blog using markdown and hugo.

### ISSUE THREAD

**Issue by siskojr** [brimsec/brim#789]
Add structure to our website so that blogging becomes the addition of content using hugo. This would allow blogging just by focusing on writing text, with the simplicity of markdown, and to publish though our current website PR process.

`hugo new posts/ZNG_great_post.md`

Our website does not use  hugo themes and needs developer work to create such foundational structure.

**Comment by jameskerr** [comment]
The PR for this is up at : https://github.com/brimsec/website/pull/30

**Comment by philrz** [comment]
We discussed this one as a group yesterday. It's on hold because it would be easiest to roll out when we have an actual blog post. Therefore we're going to just hold this in the Done column until that day comes.

**Comment by philrz** [comment]
The first blog post is now up at https://www.brimsecurity.com/blog/2020/12/december-2020-updates/
