### ISSUE TITLE
space can't be deleted if zqd goes down during ingest

### ISSUE THREAD

**Issue by mikesbrown** [brimsec/brim#830]
If I ingest data into a space and zqd is killed during ingestion, Brim notices zqd is no longer available and returns to the Spaces page. But the space that was partially ingested can't be deleted. The space is stuck in an ingest-in-progress state, even if I restart Brim (which also restarts zqd). I am able to visit the space to explore partially-ingested data, but I can't delete it.

**Comment by philrz** [comment]
The nature of this one has changed slightly. Now as of Brim commit `6f7c3be` if I kill `zqd` during import, I get this helpful error message:

![image](https://user-images.githubusercontent.com/5934157/95125644-1c40ac80-070a-11eb-933a-e525bfaaf2ba.png)

The look of the partially-ingested Space is left behind as before:

![image](https://user-images.githubusercontent.com/5934157/95125712-39757b00-070a-11eb-9a24-e63e07f1f339.png)

However, as soon as I click on it (such as if I'm going to try to delete it), I get a crash that looks like the one described in #1048:

![image](https://user-images.githubusercontent.com/5934157/95125827-5dd15780-070a-11eb-8d6b-b8679f48d458.png)

I'll make a note to check this one again after #1048 is addressed.

**Comment by philrz** [comment]
I've confirmed that as of Brim commit `a563c51` talking to `zqd` commit `e26ffa3`, it's no longer crashing. We're now back to the originally described problem:

>  I am able to visit the space to explore partially-ingested data, but I can't delete it.

**Comment by philrz** [comment]
Verified in Brim commit `014f799` talking to `zqd` commit `d05e69d`.

As shown in the attached video, now when `zqd` is killed during ingest, then the app is relaunched such that `zqd` is restarted, the partially-ingested Space can be deleted in addition to being explored.

[Verify.zip](https://github.com/brimsec/brim/files/5476644/Verify.zip)

Thanks @jameskerr!
