### ISSUE TITLE
Remove brief blank record table periods during import

### ISSUE THREAD

**Issue by alfred-landrum** [brimsec/brim#841]
When a pcap is imported into Brim, if no query is used, Brim updates the records shown as import progress is made. This currently causes brief periods of blank space in the records list while updating to the new set of records available. We should remove these blank periods.

**Comment by philrz** [comment]
In a previous group discussion on May 28th about how to address this, @jameskerr concluded an approach could be:

>If histogram is not changing a lot, let react make the changes.

We revisited the topic today to consider if we could fit this into the Brim `v0.12.0` milestone planned for the next ~2 weeks. We figured it's worth trying to accomplish if we can complete the work in 1-2 days and not have to introduce whole new components, and @jameskerr seemed to feel that was possible, so it's a target.

**Comment by philrz** [comment]
Re-opening for further treatment. We reviewed the functionality as a group today. While this change succeeded at removing the blank white flashes during import, @alfred-landrum and I were surprised that the main events page was no longer showing the most recent events up top that correspond to each incremental histogram update. We'll either address that ASAP or back out the PR before the next release if it's not something we can address in time, as we'd like to avoid having to educate users to a change in UX that we're going to change again soon after.

**Comment by philrz** [comment]
Verified in Brim commit `2e370ab`.

The first video reproduces the "before" state as it was in GA Brim tagged `v0.14.0`. When I import [wrccdc.2018-03-23.010014000000000.pcap.gz](https://archive.wrccdc.org/pcaps/2018/wrccdc.2018-03-23.010014000000000.pcap.gz) and "lean back" to let the app auto-refresh, you can see the periods when the entire events view area briefly becomes white as the newest events are filled in to correspond with the redrawn histogram.

[Repro.mp4.zip](https://github.com/brimsec/brim/files/5077045/Repro.mp4.zip)

Now repeating the same in Brim commit `2e370ab`, you can see that the equivalent refreshes happen without the white flash, which is way less distracting to the user.

[Verify.mp4.zip](https://github.com/brimsec/brim/files/5077062/Verify.mp4.zip)

FWIW, in the "lean forward" case when the user has entered a search during import and is therefore presented with a "Refresh" button to optionally click as opposed to auto-refresh (not shown in the videos), the white flash does still occur. However we've discussed this amongst ourselves and have consensus that this type of flash is less jarring for someone who actively clicks a Refesh button, so we're content to leave it as-is.

Thanks @mason-fish!
