### ISSUE TITLE
Create the New Connection Page

### ISSUE THREAD

**Issue by jameskerr** [brimsec/brim#849]
This page already exists in the app somewhere. Find it and update it to the new design. This will appear when the user does not have a "current cluster" selected for that tab.

**Comment by philrz** [comment]
Verified in Brim commit `d8b8f1e` talking to `zqd` commit `4444632`.

In addition to my local `zqd` launched by the local Brim app on my Mac, I also started a remote `zqd` in an Ubuntu VM running in VirtualBox:

```
$ /home/phil/brim/zdeps/zqd listen -l :9867 -data /home/phil/brim/run/data/spaces -config /home/phil/brim/run/zqd-config.yaml -zeekrunner /home/phil/brim/zdeps/zeek/zeekrunner
```

I then set up a Port Forwarding rule in VirtualBox to redirect `localhost:9999` on my Mac to port `9867` inside the Ubuntu VM.

As shown in the attached video, I was able to use the "New Connection" modal to connect to `localhost:9999` at which point I was connected to the remote `zqd` and able to browse data that's stored in the remote `zqd`.

[Verify.zip](https://github.com/brimsec/brim/files/5139654/Verify.zip)

Thanks @mason-fish!
