### ISSUE TITLE
Design Sign In Page

### ISSUE THREAD

**Issue by jameskerr** [brimsec/brim#850]
Update the design of our Sign In page.

**Comment by jameskerr** [comment]
Here is the design for the sign in page.

https://www.sketch.com/s/4b2957a2-910e-403c-9fda-617de055c061/a/j3yAem

**Comment by philrz** [comment]
We discussed this as a group today and agreed that the Username/Password fields can be removed since `zqd` doesn't support auth today. @jameskerr confirmed he'll address this in the implementation.
