### ISSUE TITLE
Add "Sign Out" action to Cluster Dropdown

### ISSUE THREAD

**Issue by jameskerr** [brimsec/brim#851]
On the search page, when someone clicks the cluster section of the left pane, display a native dropmenu with an option to "Sign Out".

This will remove their "current cluster" from the redux state, and the app will redirect back to the Sign In Page.

Also add a "Switch Cluster" option that does exactly the same thing. (Maybe?)

**Comment by mason-fish** [comment]
Let's do this as part of the connection detail page in #1022
