### ISSUE TITLE
Design Index Search Page

### ISSUE THREAD

**Issue by jameskerr** [brimsec/brim#852]
Using the Wireframes that Javier created, create a high-fidelity design to implement.

edit by @alfred-landrum :
This should include any visualization we display before the user has entered a search, see separate comment.

**Comment by alfred-landrum** [comment]
I'm attaching some earlier drawings:
* when a user lands on the index search page, but before a search has been entered, they're presented with a graph of data that gives an overview of archive contents, like raw & index size over time.
* we also discussed providing some extra information in the UI area that would hold a search, to avoid it looking like a large empty space.

![archive-index1](https://user-images.githubusercontent.com/704945/87472821-6b78b480-c5d5-11ea-8516-81f5e5b4a019.png)
![archive-index2](https://user-images.githubusercontent.com/704945/87472832-703d6880-c5d5-11ea-88d2-abbb51add452.png)

**Comment by alfred-landrum** [comment]
Closing this as we're no longer thinking of having separate search flows for data vs indexes.
