### ISSUE TITLE
reload is flaky

### ISSUE THREAD

**Issue by mikesbrown** [brimsec/brim#878]
[This test run](https://github.com/brimsec/brim/runs/777908057?check_suite_focus=true) failed in Spectron `app.browserWindow.reload()`. We know this is so because it's written inside an `appStep`, and that `appStep` never completed.

```
[2020-06-16 19:44:14.955 debug]: Starting step "app reload"
[2020-06-16 19:44:16.769 error]: handleError: Test hit exception: unknown error: cannot determine loading status
from unknown error: unhandled inspector error: {"code":-32000,"message":"Inspected target navigated or closed"}
```
Looks related to or actually is https://github.com/electron-userland/spectron/issues/493 .

**Comment by wolfoo2931** [comment]
for me this workaround solved the problem:

`this.app.client.execute(function() { location.reload() })`

Best Regards,
Oliver, working on [www.monsterwriter.app](https://www.monsterwriter.app/)
