### ISSUE TITLE
Store scrollposition in Viewer with searchhistory

### ISSUE THREAD

**Issue by r-franke** [brimsec/brim#899]
In extension of #894 it would be nice if we could store the scroll position alongside the history entry. This would greatly enhance the user experience while they browse 'up' and 'down' through the history to examine data.

**Possible approach** 
`Viewer.js` already has `scrollhooks` in place. So it would be possible to update the scroll position when navigating away from the current page. 

What are you thoughts about this? 

I would be willing to work on this.

**Comment by jameskerr** [comment]
I think this is a great idea, and the scroll hooks would be a perfect place to update the store.

There are two types of history in the app at the moment. The global history in the left pane, and the navigation history for the back and forward buttons next to the search bar. I think this would be a great addition to the navigation history, but I'm not convinced you'd want it in the the global history. For instance, if I pulled up a search I made yesterday, I think I'd want to see the top of my results. What do you think @r-franke? 

@brimsec/brim any of you have any thoughts?

**Comment by r-franke** [comment]
Yeah I fully agree. Recalling a previous search in the left bar should yield fresh results. I did notice during exploration today that there is interaction between the back buttons and the global history by means of highlighting the query you are on. That's something to keep in sync when implementing this.

**Comment by alfred-landrum** [comment]
hi @r-franke : we do think this is a good idea! Let us know if you'd like to work on it, otherwise we'll put it on our todo list and either @jameskerr or @mason-fish will work on it soon.

**Comment by r-franke** [comment]
I'll get started on this.

**Comment by r-franke** [comment]
I think i'm basically done except for the last step I can't seem to figure out.

In `submitSearch` I've leveraged the save routine to save the scrollposition of the current view in `History`:

```javascript
    if (save) {
      let record = Search.getRecord(state)
      let scrollPos = {x: 0, y: 0}
      if (view) {
        scrollPos.x = view.scrollLeft
        scrollPos.y = view.scrollTop
      }
      dispatch(History.push(record, time.toTs(), scrollPos))
      globalDispatch(Investigation.push(record, time.toTs()))
    }
```

Then I forward it to `brim.entries.push` to splice it in:

```javascript
    case "HISTORY_PUSH":
      return brim
        .entries(state)
        .push(action.entry, action.scrollPos)
        .data()
```
So far it's all working and I can see that the scrollpositions are registered on the state. I'm using `SearchBar/flows.js` to restore the scrollPosition:

```javascript
  goBack: (): Thunk => (dispatch, getState) => {
    dispatch(History.back())
    dispatch(Search.restore(Tab.currentEntry(getState())))
    dispatch(submitSearch(false)).then(() => {
      dispatch(Viewer.setScroll(History.getScrollPos()))
    })
  },

  goForward: (): Thunk => (dispatch, getState) => {
    dispatch(History.forward())
    dispatch(Search.restore(Tab.currentEntry(getState())))
    dispatch(submitSearch(false)).then(() => {
      dispatch(Viewer.setScroll(History.getScrollPos()))
    })
  },
```
My problem lies in the `History/selectors.js`. I thought I could solve it like this:

```javascript
  getScrollPos: (state: TabState) => {
    return state.history.scrollPositions[state.history.position]
  }
```

However I'm not able to pass the right state into `getScrollPos` from `goBack` and `goForward` in `SearchBar/flows.js`.

How would I go about solving this?

**Comment by philrz** [comment]
I'd not noticed this issue, so verification details are in the linked PR #905.
