### ISSUE TITLE
Casting not working in Brim app

### ISSUE THREAD

**Issue by philrz** [brimsec/brim#910]
This issue was reported by a community member via Slack.

The [casting example cited in the ZQL docs](https://github.com/brimsec/zq/tree/master/zql/docs/data-types#example) works via `zq` but fails in the Brim app. This repro is with Brim GA tagged `v0.12.0` with the [zq-sample-data](https://github.com/brimsec/zq-sample-data).

![image](https://user-images.githubusercontent.com/5934157/86936900-74f4af00-c0f3-11ea-9d6e-ade337d05f98.png)

**Comment by nwt** [comment]
With brimsec/zq#1008, this works as expected.

![image](https://user-images.githubusercontent.com/2574448/87614533-22a02900-c6c5-11ea-80e4-35cf9566c0ed.png)
