### ISSUE TITLE
new left pane should be open by default

### ISSUE THREAD

**Issue by alfred-landrum** [brimsec/brim#917]
@philrz hit a snag when smoke-testing the Brim v0.13.0 pre-release:

> A fresh install of v0.13.0 has the left pane opened by default, which makes sense since it's the new home of the Space picker and we want new users to see it. However, I'm finding that if I had v0.12.0 running and the left pane wasn't open, when I upgrade to v0.13.0, it's still closed. I somehow had it in my head that we'd open it up upon upgrade to spare the user from the "Where'd the Space picker go?" panic.

**Comment by philrz** [comment]
Verified in Brim GA tagged `v0.13.1`.

I first started with a fresh Brim `v0.12.0` install. I created a single Space by dragging a pcap into the app. I did _not_ have my left pane open, as I was acting as a user that only cared about access to the Space picker. I then let the app detect the availability of the new `v0.13.1` release and let it restart the app when it prompted me. When it came back up in `v0.13.1`, I can see the left pane is now open, so it's obvious to me as a user where the Space picker now lives.

![image](https://user-images.githubusercontent.com/5934157/87232399-8d72fc80-c373-11ea-81db-66d7d8d4f388.png)

Thanks @mason-fish!
