### ISSUE TITLE
Uncomment Existing Devtools Code

### ISSUE THREAD

**Issue by r-franke** [brimsec/brim#919]
Yesterday in the live stream we briefly discussed the dev tools. They where disabled because they may have caused performance issues at some times according to @jameskerr .

Maybe create a separate npm run scrip to enable the devtools. They aren't needed all the time but are sometimes handy to have up for grabs.

What are your thoughts?

**Comment by jameskerr** [comment]
@r-franke I think that it would be good to have them always enabled when in development mode. I never had real proof that those were the cause of my performance issues, so I'm happy to try having them on again. Let's turn this ticket into "Uncomment Existing Devtools Code". What do you think @mason-fish?

**Comment by philrz** [comment]
Verified in Brim commit `868c8fc`.

While I'm not a developer that represents the typical end user of this feature, @jameskerr did show me where to look for the DevTools tabs that were not there before. This includes the Redux tab:

![image](https://user-images.githubusercontent.com/5934157/88983282-70995d00-d27f-11ea-978f-64276bd013bb.png)

...and the Components and Profiler tabs that I understand to represent the React tools.

![image](https://user-images.githubusercontent.com/5934157/88983336-93c40c80-d27f-11ea-9721-e73fc5584b45.png)

![image](https://user-images.githubusercontent.com/5934157/88983430-ddacf280-d27f-11ea-8514-442a969a5681.png)

Thanks @mason-fish and @kerr!
