### ISSUE TITLE
Fix inconsistent interaction between history buttons and left sidebar

### ISSUE THREAD

**Issue by r-franke** [brimsec/brim#928]
Looking at this file made me realize we may have a bug in the code. If I submit a search with `save: false` it will not update the `History` state slice (which is what is used in the back and forward buttons) or the `Investigation` state slice (which is used for the history in the left sidebar). The main place we use `save: false` is when a user clicks on a previous search in the left sidebar.  When they click a previous search, it will update the searchbar and the viewer, but will not add an entry to the history. This results in:

```
change search input to "a",  hit enter, view results
change search input to "b",  hit enter, view results
click on a previous search in the left side bar, view results
click the "back" button

I'd expect the search input to be "b" but it is "a"
```

To fix this, here's what I think we should do.
* Always run `History.push(record, time.toTs())`
* Only run `Investigation.push(record, time.toTs())` if save === true.

Note:
There may be a case when we do in fact not want to save to the History or the Investigation. Like when clicking on the "back" and "forward" buttons. If this appears to be true, then we may need to change the save argument consider both object like: `submitSearch({history: false, investigation: false})`.

_Originally posted by @jameskerr in https://github.com/brimsec/brim/pull/905_

**Comment by philrz** [comment]
Verified in Brim commit `f2676ff`.

First I circled back to Brim GA tagged `v0.15.1` to reacquaint myself with the repro described above.

[Repro.mp4.zip](https://github.com/brimsec/brim/files/5119718/Repro.mp4.zip)

Then on Brim commit `f2676ff`, I can see that now hitting the Back button brings up the search input "b" as intended.

[Verify.mp4.zip](https://github.com/brimsec/brim/files/5119719/Verify.mp4.zip)

Thanks @r-franke!
