### ISSUE TITLE
Double clicking on two different rows, acts like double clicking on the second row

### ISSUE THREAD

**Issue by jameskerr** [brimsec/brim#966]
**Describe the bug**
Quickly clicking two different logs will trigger the "onDoubleClick" handler for the latter log. 

**Expected behavior**
I'd expect that you'd only get the detail view by clicking twice, quickly on the same log line.

**Comment by philrz** [comment]
Verified in Brim commit `9ba4ec9`. I'm skipping my usual ceremonial video proof, as the clicks don't really come across in video form. Suffice to say, after getting the hang of the original repro by running at commit that didn't have the fix, I confirmed that now I can quickly single-click between two different events and it does _not_ pop up a Log Detail window like it was. Also, a double-click on the same event is still bringing up the Log Detail window as intended.

Thanks @mason-fish!
