### ISSUE TITLE
"Packets" button not activating after lots of infinite scrolling

### ISSUE THREAD

**Issue by philrz** [brimsec/brim#979]
Reproducing this issue is unfortunately somewhat complicated, but I think I've come up with a fairly reliable recipe at least. Repro is on Brim commit `7c8527a` talking to `zqd` commit `a1a817e`.

1. Start with a pristine instance of the app (i.e. `appState.json` and Spaces directories removed before launching).

2. Import an uncompressed copy of [wrccdc.2018-03-23.010014000000000.pcap.gz](https://archive.wrccdc.org/pcaps/2018/wrccdc.2018-03-23.010014000000000.pcap.gz) and let generation of Zeek logs completely finish.

3. Drag down the vertical scrollbar to trigger infinite scroll. I keep wiggling the mouse pointer up & down near the bottom of the scrollbar, which seems to help re-triggering the infinite scroll. I keep doing this for over 30 seconds and use a stopwatch to make sure I've waited at least that long.

4. Single-click on one of the `conn` records in view. At this point I consistently find the "Packets" button does _not_ activate, giving me the impression as a user that no flow is available in the original pcap corresponding to this `conn` record.

5. Double-click the same `conn` record. In the separate Log Detail window that opens, I find the "Packets" button _is_ now activated.

Steps 3-5 are shown in the attached video. It's not shown in the video, but clicking the "Packets" button _does_ bring up the flow successfully in Wireshark.

[Repro.mp4.zip](https://github.com/brimsec/brim/files/5054194/Repro.mp4.zip)

Note that due to the timing issues with triggering infinite scroll, it would be nearly impossible to click the exact same flow in each repro. However, I've reproduced this several times using the same recipe and found that clicking _any_ `conn` record that far down in the scrolling reproduces the issue.

It also seems that the infinite scrolling may somehow be important to triggering the issue. For example, after reproducing the behavior with a particular flow, I've created ZQL to isolate the same flow via 4-tuple and executed that ZQL in a fresh version of the app after re-importing the same PCAP, but in that case I've been ale to reliably activate the "Packets" button on the single `conn` record that comes up in that case.

Finally, I had a conversation on Slack with @jameskerr about what triggers the "Packets" button to activate. His explanation:

> We take the `uid` from the log if there is one, then we execute this query and see if there is a `conn` event.
> ```
> uid=${uid} or ${uid} in conn_uids or ${uid} in uids or referenced_file.uid=${uid} | head ${UID_CORRELATION_LIMIT}
> ```
> With the limit being 100
> Then if there is a `conn` log in that set, and the space has “packet_support” set to true, we’ll enable the packets button.

Since this confirmed a backend query was involved, I used Wireshark to isolate the backend query in the non-working and working cases. Here's what comes up in the TCP byte stream (includes both directions of the conversation):

### Button not activating

```
POST /search?format=zjson HTTP/1.1
Host: localhost:9867
Connection: keep-alive
Content-Length: 1019
sec-ch-ua: 
Origin: file://
Sec-Fetch-Dest: empty
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Brim/0.14.0 Chrome/78.0.3904.130 Electron/7.3.2 Safari/537.36
Content-Type: text/plain;charset=UTF-8
Accept: */*
Sec-Fetch-Site: cross-site
Sec-Fetch-Mode: cors
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US

{"proc":{"op":"SequentialProc","procs":[{"op":"FilterProc","filter":{"op":"LogicalOr","left":{"op":"LogicalOr","left":{"op":"LogicalOr","left":{"op":"CompareField","comparator":"=","field":{"op":"FieldRead","field":"uid"},"value":{"op":"Literal","type":"string","value":"C52cuf1JdFLKEYXdv3"}},"right":{"op":"CompareField","comparator":"in","field":{"op":"FieldRead","field":"conn_uids"},"value":{"op":"Literal","type":"string","value":"C52cuf1JdFLKEYXdv3"}}},"right":{"op":"CompareField","comparator":"in","field":{"op":"FieldRead","field":"uids"},"value":{"op":"Literal","type":"string","value":"C52cuf1JdFLKEYXdv3"}}},"right":{"op":"CompareField","comparator":"=","field":{"op":"FieldCall","fn":"RecordFieldRead","field":{"op":"FieldRead","field":"referenced_file"},"param":"uid"},"value":{"op":"Literal","type":"string","value":"C52cuf1JdFLKEYXdv3"}}}},{"op":"HeadProc","count":100}]},"span":{"ts":{"sec":1521835102,"ns":636000000},"dur":{"sec":111,"ns":660000000}},"space":"sp_1fvlMFN03xJzNXhmbo4S729sBEp","dir":-1}HTTP/1.1 200 OK
Content-Type: application/x-ndjson
X-Request-Id: 47
Date: Tue, 11 Aug 2020 00:45:30 GMT
Transfer-Encoding: chunked

23
{"type":"TaskStart","task_id":0}



35
{"type":"SearchEnd","channel_id":0,"reason":"eof"}



ca
{"type":"SearchStats","start_time":{"sec":1597106730,"ns":464115000},"update_time":{"sec":1597106730,"ns":921383000},"bytes_read":38147100,"bytes_matched":0,"records_read":407000,"records_matched":0}



1f
{"type":"TaskEnd","task_id":0}

0
```

### Button activating when opening Log Detail window

```
POST /search?format=zjson HTTP/1.1
Host: localhost:9867
Connection: keep-alive
Content-Length: 1019
Origin: file://
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Brim/0.14.0 Chrome/78.0.3904.130 Electron/7.3.2 Safari/537.36
Content-Type: text/plain;charset=UTF-8
Accept: */*
Sec-Fetch-Site: cross-site
Sec-Fetch-Mode: cors
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US

{"proc":{"op":"SequentialProc","procs":[{"op":"FilterProc","filter":{"op":"LogicalOr","left":{"op":"LogicalOr","left":{"op":"LogicalOr","left":{"op":"CompareField","comparator":"=","field":{"op":"FieldRead","field":"uid"},"value":{"op":"Literal","type":"string","value":"C52cuf1JdFLKEYXdv3"}},"right":{"op":"CompareField","comparator":"in","field":{"op":"FieldRead","field":"conn_uids"},"value":{"op":"Literal","type":"string","value":"C52cuf1JdFLKEYXdv3"}}},"right":{"op":"CompareField","comparator":"in","field":{"op":"FieldRead","field":"uids"},"value":{"op":"Literal","type":"string","value":"C52cuf1JdFLKEYXdv3"}}},"right":{"op":"CompareField","comparator":"=","field":{"op":"FieldCall","fn":"RecordFieldRead","field":{"op":"FieldRead","field":"referenced_file"},"param":"uid"},"value":{"op":"Literal","type":"string","value":"C52cuf1JdFLKEYXdv3"}}}},{"op":"HeadProc","count":100}]},"span":{"ts":{"sec":1521835102,"ns":636000000},"dur":{"sec":111,"ns":696000000}},"space":"sp_1fvlMFN03xJzNXhmbo4S729sBEp","dir":-1}HTTP/1.1 200 OK
Content-Type: application/x-ndjson
X-Request-Id: 51
Date: Tue, 11 Aug 2020 00:46:06 GMT
Transfer-Encoding: chunked

23
{"type":"TaskStart","task_id":0}



cb
{"type":"SearchStats","start_time":{"sec":1597106766,"ns":998738000},"update_time":{"sec":1597106767,"ns":504964000},"bytes_read":35693265,"bytes_matched":89,"records_read":390117,"records_matched":1}



649
{"type":"SearchRecords","channel_id":0,"records":[{"id":29,"type":[{"name":"_path","type":"string"},{"name":"ts","type":"time"},{"name":"uid","type":"bstring"},{"name":"id","type":[{"name":"orig_h","type":"ip"},{"name":"orig_p","type":"port"},{"name":"resp_h","type":"ip"},{"name":"resp_p","type":"port"}]},{"name":"proto","type":"zenum"},{"name":"service","type":"bstring"},{"name":"duration","type":"duration"},{"name":"orig_bytes","type":"uint64"},{"name":"resp_bytes","type":"uint64"},{"name":"conn_state","type":"bstring"},{"name":"local_orig","type":"bool"},{"name":"local_resp","type":"bool"},{"name":"missed_bytes","type":"uint64"},{"name":"history","type":"bstring"},{"name":"orig_pkts","type":"uint64"},{"name":"orig_ip_bytes","type":"uint64"},{"name":"resp_pkts","type":"uint64"},{"name":"resp_ip_bytes","type":"uint64"},{"name":"tunnel_parents","type":"set[bstring]"},{"name":"geo","type":[{"name":"orig","type":[{"name":"country_code","type":"bstring"},{"name":"region","type":"bstring"},{"name":"city","type":"bstring"},{"name":"latitude","type":"float64"},{"name":"longitude","type":"float64"}]},{"name":"resp","type":[{"name":"country_code","type":"bstring"},{"name":"region","type":"bstring"},{"name":"city","type":"bstring"},{"name":"latitude","type":"float64"},{"name":"longitude","type":"float64"}]}]}],"aliases":[{"name":"zenum","type":"string"}],"values":["conn","1521835214.297815","C52cuf1JdFLKEYXdv3",["10.236.58.83","47941","10.47.1.50","15765"],"tcp",null,"0.000034","0","0","S0",null,null,"0","S","2","80","0","0",null,[[null,null,null,null,null],[null,null,null,null,null]]]}]}



35
{"type":"SearchEnd","channel_id":0,"reason":"eof"}



cb
{"type":"SearchStats","start_time":{"sec":1597106766,"ns":998738000},"update_time":{"sec":1597106767,"ns":528221000},"bytes_read":38191521,"bytes_matched":89,"records_read":407495,"records_matched":1}



1f
{"type":"TaskEnd","task_id":0}

0
```

If I isolate just the query portions, run each through `jq`, and `diff` them, I find only one difference:

```
$ echo '{"proc":{"op":"SequentialProc","procs":[{"op":"FilterProc","filter":{"op":"LogicalOr","left":{"op":"LogicalOr","left":{"op":"LogicalOr","left":{"op":"CompareField","comparator":"=","field":{"op":"FieldRead","field":"uid"},"value":{"op":"Literal","type":"string","value":"C52cuf1JdFLKEYXdv3"}},"right":{"op":"CompareField","comparator":"in","field":{"op":"FieldRead","field":"conn_uids"},"value":{"op":"Literal","type":"string","value":"C52cuf1JdFLKEYXdv3"}}},"right":{"op":"CompareField","comparator":"in","field":{"op":"FieldRead","field":"uids"},"value":{"op":"Literal","type":"string","value":"C52cuf1JdFLKEYXdv3"}}},"right":{"op":"CompareField","comparator":"=","field":{"op":"FieldCall","fn":"RecordFieldRead","field":{"op":"FieldRead","field":"referenced_file"},"param":"uid"},"value":{"op":"Literal","type":"string","value":"C52cuf1JdFLKEYXdv3"}}}},{"op":"HeadProc","count":100}]},"span":{"ts":{"sec":1521835102,"ns":636000000},"dur":{"sec":111,"ns":660000000}},"space":"sp_1fvlMFN03xJzNXhmbo4S729sBEp","dir":-1}' | jq . > not-working.json 

$ echo '{"proc":{"op":"SequentialProc","procs":[{"op":"FilterProc","filter":{"op":"LogicalOr","left":{"op":"LogicalOr","left":{"op":"LogicalOr","left":{"op":"CompareField","comparator":"=","field":{"op":"FieldRead","field":"uid"},"value":{"op":"Literal","type":"string","value":"C52cuf1JdFLKEYXdv3"}},"right":{"op":"CompareField","comparator":"in","field":{"op":"FieldRead","field":"conn_uids"},"value":{"op":"Literal","type":"string","value":"C52cuf1JdFLKEYXdv3"}}},"right":{"op":"CompareField","comparator":"in","field":{"op":"FieldRead","field":"uids"},"value":{"op":"Literal","type":"string","value":"C52cuf1JdFLKEYXdv3"}}},"right":{"op":"CompareField","comparator":"=","field":{"op":"FieldCall","fn":"RecordFieldRead","field":{"op":"FieldRead","field":"referenced_file"},"param":"uid"},"value":{"op":"Literal","type":"string","value":"C52cuf1JdFLKEYXdv3"}}}},{"op":"HeadProc","count":100}]},"span":{"ts":{"sec":1521835102,"ns":636000000},"dur":{"sec":111,"ns":696000000}},"space":"sp_1fvlMFN03xJzNXhmbo4S729sBEp","dir":-1}' | jq . > working.json

$ diff not-working.json working.json 
87c87
<       "ns": 660000000
---
>       "ns": 696000000
```

The slightly longer value for the duration is suspicious. I saw the same `diff` on multiple repros. Is it possible that there's different query generators for the main events panel and Log Detail, with a bug in the former?

**Comment by mattnibs** [comment]
Does not appear to be an issue with zqd. I'll explain.

The ts of the target conn record in the above data set: 1521835214.297815
The range of the bad query: 1521835102.636 - 1521835214.296000
The range of the good query: 1521835102.636 - 1521835214.332000

The conn log is not in the range of the bad query.

Stepping back, I would change the heuristic for getting the conn_log (client side). If a record is selected and is not a conn log (i.e. _path=conn) the brim client should get the uid for the record and issue a reverse direction query:
```
_path=conn uid=${uid} | HEAD 1
```
The time window of the query should be [0, record.ts]

Once the conn log is in hand, the client should issue the query mentioned by @jameskerr with a time range of [conn.ts, conn.ts+conn.duration]

**Comment by philrz** [comment]
Verified in Brim commit `d8b8f1e` talking to `zqd` commit `4444632`.

As shown in the attached video, now after spending 30 seconds wiggling the mouse to trigger infinite scroll, I can click a `conn` record and the Packets button is now activated. I can click it and successfully open the extracted flow in Wireshark.

[Verify.mp4.zip](https://github.com/brimsec/brim/files/5139697/Verify.mp4.zip)

Thanks @jameskerr!
