### ISSUE TITLE
"Syntax docs" window is unusable

### ISSUE THREAD

**Issue by philrz** [brimsec/brim#982]
Repro is in Brim `v0.14.0`.

There's a link to the ZQL docs from the pull-down menu via **Help > Query Syntax Docs** that works as I'd expect, in that it opens up the docs in my browser. However, I recently noticed (per the attached video) that there's also a "Syntax docs" option available in the vertical "..." menu to the right of the search bar. When clicked, I find I can't move the window, nor can I click on any of the links in it that go to the other docs pages. As a user, I find it unusable in its current form.

[Repro.zip](https://github.com/brimsec/brim/files/5059762/Repro.zip)

I'd suggest that we either make it behave more like the one from the **Help** pull-down or remove it entirely.

**Comment by philrz** [comment]
Current thinking is we should just remove it for now.

**Comment by r-franke** [comment]
Working on it.

**Comment by philrz** [comment]
Verified in Brim commit `7cf09ff`. Per the attached video, the option remains in the menu, but now when clicked it behaves like the one in the **Help** pull-down such that it opens in my regular browser window that I can move around, click links in it, etc.

[Verify.zip](https://github.com/brimsec/brim/files/5133366/Verify.zip)

Thanks @r-franke!
