### ISSUE TITLE
Open/closing log detail menu during pcap ingest causes cancellation

### ISSUE THREAD

**Issue by mattnibs** [brimsec/brim#994]
Steps to reproduce:
1. Start ingesting large enough pcap to do the following steps
2. Wait for the space to become queryable
3. While ingesting, double click a conn record which brings up a separate log detail window
Close the log detail window
4. See this error:
![Screen Shot 2020-08-13 at 12.05.08 PM.png](https://images.zenhubusercontent.com/5e84afbcb65644b052b81bc8/d9acd63c-5bf4-4a1c-abd2-3c2815b6224f)

**Comment by philrz** [comment]
![image](https://user-images.githubusercontent.com/5934157/90193325-89bf0500-dd79-11ea-9b39-0a5f12b0b0da.png)

**Comment by philrz** [comment]
Verified in Brim `f2676ff` talking to `zqd` commit `b7023d5`.

Per the attached video, now when I close the Log Detail window that pops up, there's no error and import continues unaffected.

[Verify.zip](https://github.com/brimsec/brim/files/5120586/Verify.zip)

Thanks @mason-fish!
